(function(){
  'use strict';
  const E=window.JiaoyingEngine,store=window.JiaoyingState.create(),$=id=>document.getElementById(id);
  const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let page='warning',selected='all',busy=false,draft=null,receiptText='已通知，但家属还没到，需要人员陪同接送。',receiptHome='H5',sample=0;
  let partialDraft={version:0,ack:false,note:''};
  const assistant=window.JiaoyingAssistant.create({store,render,notify,onGenerate:generate,onBridge:async event=>{if(busy)throw new Error('正在计算，请稍候');store.setEvent(event,true);await generate();},onReview:(id,text)=>{receiptHome=id;receiptText=text;const parsed=E.parseReceipt(text);draft={id,text,parsed,checked:{assistance:parsed.needsAssistance,wheelchair:parsed.needsWheelchair}};location.hash='feedback';render();requestAnimationFrame(()=>{$('receipt-text')?.focus();$('receipt-result')?.scrollIntoView({block:'center'});});}});
  const S=()=>store.data.scenario,D=()=>store.data,locked=()=>D().phase!=='preparation';
  const total=()=>S().households.reduce((n,h)=>n+h.people,0),assigned=id=>store.fresh()?D().plan.routes.find(r=>r.stops.some(st=>st.id===id)):null;
  const name=id=>S().households.find(h=>h.id===id)?.name||S().shelters.find(s=>s.id===id)?.name||S().nodes.find(n=>n.id===id)?.label||id;
  const stageLabels={waiting:'待接送',boarded:'已登记上车',arrived:'到达待核验',verified:'已人工核验'};
  const b=(text,action,kind='primary',extra='')=>`<button class="button ${kind}" data-action="${action}" ${extra}>${text}</button>`;
  const link=(text,to,kind='primary')=>`<a class="button ${kind}" href="#${to}">${text}</a>`;
  const tag=(text,color='')=>`<span class="tag ${color}">${text}</span>`;
  const head=(title,sub,right='')=>`<div class="panel-head"><div><h2>${title}</h2>${sub?`<small>${sub}</small>`:''}</div>${right}</div>`;
  const stat=(label,value,unit,foot,featured=false)=>`<div class="stat ${featured?'featured':''}"><div class="stat-label">${label}<span>◇</span></div><div class="stat-value">${value}<small>${unit}</small></div><div class="stat-foot">${foot}</div></div>`;
  const home=h=>`<div class="home-cell"><span class="home-number">${h.id.slice(1).padStart(2,'0')}</span><span><strong>${esc(h.name)}</strong><small>${h.people} 人 · 包保员 ${h.id.slice(1).padStart(2,'0')}</small></span></div>`;
  const needs=h=>`<div class="tags">${h.priority===3?tag('优先转移','orange'):''}${h.assistance?tag('上门协助','blue'):''}${h.wheelchair?tag('轮椅位','blue'):''}${h.priority===1&&!h.assistance?tag('常规接送'):''}</div>`;
  function notify(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').classList.remove('visible'),4500);}
  function planLabel(){return !D().plan?'尚未规划':!store.fresh()?'旧方案待复核':locked()?'执行中 · 路线冻结':D().confirmed?(D().plan.complete?'已确认 · 待出发':'部分已确认 · 待协调'):D().plan.complete?'草案待确认':'部分安排 · 待协调';}
  function heading(title,description,action){return `<section class="page-heading"><div><span class="eyebrow">JIAOYING / FLOOD RESPONSE</span><h1>${title}</h1><p>${description}</p></div><div class="heading-action">${action||''}</div></section>`;}
  function timeline(limit=5){return `<section class="panel">${head('行动记录','当前浏览器内保存；导出可保留输入、方案与记录')}<ol class="timeline">${D().log.slice(0,limit).map(l=>`<li><time>事件 ${String(l.sequence).padStart(2,'0')} · 输入 v${l.version}</time>${esc(l.message)}</li>`).join('')}</ol></section>`;}
  function warning(){
    const contacts=Object.values(D().contact),ack=contacts.filter(c=>c.ack).length,contacted=contacts.filter(c=>c.contacted).length;
    const flow=[['warning','预警叫应',D().sent?'演练任务已发布':'发布本次转移任务',D().sent],['ledger','核对人员与资源',`${S().households.length} 户 · ${S().vehicles.length} 辆车`,contacted===S().households.length],['dispatch','路径与车辆安排',planLabel(),!!D().confirmed],['feedback','反馈与核验',locked()?'模拟执行跟踪':'等待方案确认',locked()]];
    return heading('预警叫应','沿用叫应的基层场景，把预警落实到家庭、责任人和接送行动。',D().sent?link('核对人员与资源 →','ledger'):b('模拟发布叫应任务','publish'))+
      `<div class="workflow">${flow.map((f,i)=>`<a href="#${f[0]}" class="flow-item ${f[3]?'done':i===flow.findIndex(x=>!x[3])?'next':''}"><span class="step">${f[3]?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${f[1]}</strong><small>${f[2]}</small></span><span class="arrow">→</span></a>`).join('')}</div>`+
      `<div class="warning-hero"><span class="weather-icon">☂</span><div>${tag('虚构预警 · 非实时气象','orange')}<h2>暴雨情景，启动人员转移准备</h2><p>任务 JY-EX-001 · 青岚镇东西两岸 · 包保员逐户联系，核对协助需求</p></div><div class="right"><strong>${D().sent?'任务已发布':'等待发布'}</strong>仅模拟通知与联系记录</div></div>`+
      `<div class="stats">${stat('本次转移对象',total(),'人',`${S().households.length} 户，人数包含同行者`)}${stat('重点家庭',S().households.filter(h=>h.priority>1).length,'户','优先转移或需要上门协助')}${stat('包保员已接收',ack,`/ ${contacts.length}`,'收到任务不代表完成联系',true)}${stat('已联系家庭',contacted,`/ ${contacts.length}`,'不代表已上车或已转移')}</div>`+
      `<section class="panel">${head('逐户叫应台账','演练角色与联系状态；本次全部家庭均纳入接送计算',tag(D().sent?'任务已发布':'待发布任务',D().sent?'green':''))}<div class="table-wrap"><table><thead><tr><th>家庭 / 包保角色</th><th>协助需求</th><th>任务接收</th><th>联系家庭</th><th>演练操作</th></tr></thead><tbody>${S().households.map(h=>{const c=D().contact[h.id];return `<tr><td>${home(h)}</td><td>${needs(h)}</td><td>${tag(c.ack?'已确认收到':D().sent?'等待接收':'尚未发布',c.ack?'green':'')}</td><td>${tag(c.contacted?'已联系到':'待联系',c.contacted?'green':'orange')}</td><td><div class="row-actions">${b('包保员收到','ack','quiet small',`data-id="${h.id}" ${!D().sent||c.ack?'disabled':''} aria-label="${h.name}包保员收到"`)}${b('登记已联系','contact','secondary small',`data-id="${h.id}" ${!c.ack||c.contacted?'disabled':''} aria-label="${h.name}登记已联系"`)}</div></td></tr>`;}).join('')}</tbody></table></div></section>`+
      `<div class="columns section-gap"><section class="panel">${head('本次升级关注什么','从通知闭环进一步走向接送行动')}<div class="panel-body"><ul class="check-list"><li><strong>① 发现“已通知，但仍走不了”的家庭</strong><small>回执中发现陪同、轮椅等需求，人工核实后更新台账。</small></li><li><strong>② 让人、车、路、安置点一起参与规划</strong><small>联合安排车辆和接送顺序，显示未能安排的对象与原因。</small></li><li><strong>③ 把确认、上车、到达和核验分开</strong><small>出发前条件变化必须重算；文本上报不能自动完成转移。</small></li></ul></div></section>${timeline(4)}</div>`;
  }
  function ledger(){
    const resource=(r,kind)=>`<article class="resource ${r.available?'':'off'}"><div class="resource-top"><strong>${esc(r.name)}</strong>${tag(r.available?'可用':'停用',r.available?'green':'')}</div><div class="capacity">${r.capacity}<small>人${kind==='vehicles'?' / 总名额':' / 可接收'}</small></div><p>${kind==='vehicles'?(r.wheelchair?'含 1 个轮椅位 · 单趟接送':'普通车辆 · 单趟接送'):'容量参与车辆联合分配'}</p>${b('编辑资源','edit-resource','quiet small',`data-id="${r.id}" data-kind="${kind}" ${locked()?'disabled':''} aria-label="编辑${r.name}"`)}</article>`;
    return heading('人员与资源','修改人数、适配需求或可用资源，保存后重新计算接送方案。',link('进入路径与调度 →','dispatch'))+
      (locked()?'<div class="notice warning"><strong>执行中的人员与资源已冻结</strong><p>新增情况请在转移反馈页登记为待协调事项。本版不支持途中重新分配。</p></div>':`<div class="notice"><strong>一场演练，一份台账。</strong> 本次始终对全部 ${S().households.length} 户 ${total()} 人规划；编辑取消不生效，保存计算条件才使旧方案失效。</div>`)+
      `<section class="panel">${head('转移对象','同行者已计入；协助需求可与优先转移、轮椅需求同时存在',tag(`输入 v${D().version}`,'blue'))}<div class="table-wrap"><table><thead><tr><th>家庭 / 人数</th><th>需求标签</th><th>规划优先级</th><th>接人用时</th><th>最近回执</th><th>操作</th></tr></thead><tbody>${S().households.map(h=>`<tr><td>${home(h)}</td><td>${needs(h)}</td><td>${['','常规接送','需协助','优先转移'][h.priority]}</td><td>${h.service} 分钟</td><td>${esc(h.response)}</td><td>${b('编辑','edit-home','quiet small',`data-id="${h.id}" ${locked()?'disabled':''} aria-label="编辑${h.name}"`)}</td></tr>`).join('')}</tbody></table></div></section>`+
      `<div class="columns section-gap"><section class="panel">${head('接送车辆','轮椅位包含在总名额内；本版每辆适配车仅 1 个轮椅位')}<div class="panel-body resource-grid">${S().vehicles.map(r=>resource(r,'vehicles')).join('')}</div></section><section class="panel">${head('安置点','此处容量指本次演练可用接收名额')}<div class="panel-body resource-grid" style="grid-template-columns:1fr 1fr">${S().shelters.map(r=>resource(r,'shelters')).join('')}</div></section></div>`+
      `<div class="notice section-gap no-margin"><strong>当前规则由演练设定。</strong> 需要协助时优先级至少为“需协助”，接人时间至少 5 分钟；轮椅需求至少 6 分钟。实际阈值和优先规则需与业务人员核实。</div>`;
  }
  function mapSvg(){
    const s=S(),p=store.fresh()?D().plan:null,n=Object.fromEntries(s.nodes.map(x=>[x.id,x]));
    let svg='<defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#e7edf2"/></pattern></defs><rect width="820" height="540" fill="#f1f5f8"/><rect width="820" height="540" fill="url(#grid)"/><path d="M426 -20 C466 63 414 98 446 173 S480 265 440 330 S433 435 470 570" fill="none" stroke="#d7e9f1" stroke-width="46"/><text x="48" y="38" class="region-label">西岸片区</text><text x="665" y="49" class="region-label">东岸片区</text><text x="440" y="380" class="region-label" transform="rotate(80 440 380)">青岚河 · 示意</text>';
    for(const e of s.edges){const a=n[e.from],z=n[e.to];svg+=`<g><title>${esc(a.label)}至${esc(z.label)}，${e.minutes} 分钟，${e.open?'演练可通行':'封闭'}</title><line x1="${a.x}" y1="${a.y}" x2="${z.x}" y2="${z.y}" stroke="${e.open?'#d8e2eb':'#e6bdbc'}" stroke-width="10" stroke-linecap="round"/><line x1="${a.x}" y1="${a.y}" x2="${z.x}" y2="${z.y}" stroke="${e.open?'white':'#c87c76'}" stroke-width="${e.open?6:3}" ${e.open?'':'stroke-dasharray="6 5"'}/></g>`;}
    if(p)for(const r of p.routes){if(!r.stops.length||(selected!=='all'&&selected!==r.vehicleId))continue;const v=s.vehicles.find(x=>x.id===r.vehicleId),offset=selected==='all'?(s.vehicles.indexOf(v)-1)*2.5:0;for(const seg of r.segments)svg+=`<polyline class="route-line" points="${seg.nodes.map(id=>`${n[id].x+offset},${n[id].y+offset}`).join(' ')}" stroke="${v.color}" stroke-width="${selected==='all'?3.7:5}"><title>${v.name}：${esc(name(seg.from))} → ${esc(name(seg.to))}，行驶 ${seg.minutes} 分钟</title></polyline>`;}
    for(const [id,label,y] of [['east','东桥',247],['north','北桥',62]]){const e=s.edges.find(e=>e.id===id);svg+=`<text x="453" y="${y}" text-anchor="middle" class="road-label" style="fill:${e.open?'#8192a8':'#ba6f66'}">${label} · ${e.open?e.minutes+' 分':'已封闭'}</text>`;if(!e.open)svg+=`<circle cx="454" cy="${id==='east'?220:82}" r="10" fill="#cc7b73"/><text x="454" y="${id==='east'?224:86}" text-anchor="middle" fill="white" font-size="16">×</text>`;}
    for(const x of s.nodes){if(x.kind==='junction'){svg+=`<circle cx="${x.x}" cy="${x.y}" r="3" fill="#bfcedd"/>`;continue;}let color='#6985a7',shape='',label=x.label;
      if(x.kind==='home'){const h=s.households.find(h=>h.id===x.id),r=p?.routes.find(r=>r.stops.some(st=>st.id===x.id)),v=r?s.vehicles.find(v=>v.id===r.vehicleId):null,isSelected=selected==='all'||r?.vehicleId===selected;color=isSelected&&v?v.color:'#98a9bd';label=h.name+' · '+h.people+' 人';const number=selected!=='all'&&r?.vehicleId===selected?r.stops.findIndex(st=>st.id===x.id)+1:x.id.slice(1).padStart(2,'0');shape=`<circle cx="${x.x}" cy="${x.y}" r="17" fill="white" stroke="${color}" stroke-width="2"/><text x="${x.x}" y="${x.y+4}" text-anchor="middle" font-size="12" fill="${color}">${number}</text>${h.priority>1?`<circle cx="${x.x+13}" cy="${x.y-13}" r="4" fill="#d5a05b" stroke="white" stroke-width="1.5"/>`:''}`;
      }else if(x.kind==='shelter'){const sh=s.shelters.find(sh=>sh.id===x.id);color=sh.available?'#669985':'#a99b9b';shape=`<rect x="${x.x-18}" y="${x.y-18}" width="36" height="36" rx="9" fill="${sh.available?'#e3f0e9':'#eee8e7'}" stroke="${color}"/><text x="${x.x}" y="${x.y+6}" text-anchor="middle" font-size="25" fill="${color}">⌂</text>`;
      }else shape=`<rect x="${x.x-19}" y="${x.y-19}" width="38" height="38" rx="10" fill="#2f4b6e"/><text x="${x.x}" y="${x.y+5}" text-anchor="middle" font-size="13" fill="white">起点</text>`;
      svg+=`<g><title>${esc(label)}</title>${shape}<text x="${x.x}" y="${x.y+36}" text-anchor="middle" class="node-label">${esc(label)}</text></g>`;
    }
    return `<svg class="map-svg" viewBox="0 0 820 540" role="img" aria-label="虚构路网${selected==='all'?'和所有候选路线':'及'+selected+'接送路线'}">${svg}</svg>`;
  }
  function routeDetail(){
    if(!store.fresh()||selected==='all')return '<div class="map-foot">点击一辆车，查看接送顺序和逐段道路。<b>圆点橙标：重点家庭</b></div>';
    const r=D().plan.routes.find(r=>r.vehicleId===selected),v=S().vehicles.find(v=>v.id===selected);if(!r?.stops.length)return '<div class="map-foot">该车本次未安排任务。</div>';
    const legNames=seg=>seg.nodes.map(id=>esc(name(id))).join(' → ');
    return `<div class="route-detail"><h3>${v.name} · 逐站接送说明</h3><div class="stop-list"><div class="stop"><span class="step-number">起</span><div><strong>车辆集结点出发</strong><small>${r.people} / ${v.capacity} 个名额${v.wheelchair?' · 适配 1 个轮椅位':''}</small></div><span class="time">+0 分</span></div>${r.stops.map((st,i)=>`<div class="stop"><span class="step-number">${i+1}</span><div><strong>${esc(name(st.id))} · 接 ${st.people} 人</strong><small>${legNames(r.segments[i])}<br>行驶 ${r.segments[i].minutes} 分 · 接人 ${st.depart-st.arrival} 分</small></div><span class="time">+${st.arrival} 分到户</span></div>`).join('')}<div class="stop"><span class="step-number">终</span><div><strong>${esc(name(r.shelterId))}</strong><small>${legNames(r.segments.at(-1))}<br>最终行驶 ${r.segments.at(-1).minutes} 分</small></div><span class="time">+${r.finish} 分抵达</span></div></div><p class="hint no-margin">地图中的数字为本车接人顺序。时间包含沿途接人，全部为演练估计。</p></div>`;
  }
  function comparison(){
    if(!store.fresh())return `<section class="panel section-gap">${head('同条件方案对比','两种方法使用相同家庭、车辆、路况与容量')}<div class="empty"><strong>${D().plan?'输入已变化，请重新计算两种方案':'生成接送草案后查看对比'}</strong><p>本版不预填“效率提升百分比”。</p></div></section>`;
    const p=D().plan,q=D().baseline,same=p.mask===q.mask;
    const rows=[['安排人数',q.servedPeople+' / '+total()+' 人',p.servedPeople+' / '+total()+' 人'],['重点家庭覆盖',(q.urgent+q.assisted)+' 户',(p.urgent+p.assisted)+' 户'],['重点人员平均到户等待',q.servedPeople?q.priorityAverage.toFixed(1)+' 分':'—',p.servedPeople?p.priorityAverage.toFixed(1)+' 分':'—'],['最后抵达安置点',q.servedPeople?'+'+q.finish+' 分':'—',p.servedPeople?'+'+p.finish+' 分':'—'],['全部车辆行驶时间',q.drive+' 分',p.drive+' 分'],['约束违规',E.validatePlan(D().planInput,q).length+' 项',E.validatePlan(D().planInput,p).length+' 项']];
    return `<section class="panel section-gap">${head('同条件方案对比',`共同输入 v${D().planVersion} · 简单基线也遵守车辆、道路与安置约束`,tag(same?'接送对象一致':'接送对象不同',same?'green':'orange'))}<div class="table-wrap"><table class="comparison"><thead><tr><th>比较指标</th><th>简单就近派车基线</th><th class="highlight">联合调度草案</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="highlight">${r[2]}</td></tr>`).join('')}</tbody></table></div><div class="compare-note">${same?'接送对象一致，可比较本情景内的时间差；不同目标存在权衡，不保证所有指标都改善。':'两方案接送对象不同，应先比较覆盖与未安排家庭，时间不能解读为同一批人的效率提升。'}<br>基线：按优先级、家庭编号依次安排到最早可到户的可行车辆，首次选定安置点后不改变。不代表真实人工派车水平。</div></section>`;
  }
  function dispatch(){
    const fresh=store.fresh(),p=fresh?D().plan:null,events=[['bridge','东桥封闭',!S().edges.find(e=>e.id==='east').open],['north','北桥封闭',!S().edges.find(e=>e.id==='north').open],['vehicle','2 号车停用',!S().vehicles[1].available],['shelter','体育馆暂停',!S().shelters[1].available]];
    let plans=!p?`<div class="empty"><span class="symbol">⌁</span><strong>${D().plan?'旧方案已失效':'为每一户安排接送'}</strong><p>${D().plan?'输入条件改变，旧路线不再作为当前方案显示。请重新生成。':'同时考虑道路、车辆、接送顺序、轮椅适配与安置容量。'}</p></div>`:
      `<div class="plan-summary ${p.complete?'':'partial'}">${p.complete?'✓':'!'} ${p.servedHouseholds} / ${p.totalHouseholds} 户 · ${p.servedPeople} / ${p.totalPeople} 人已安排</div>${p.routes.filter(r=>r.stops.length).map(r=>{const v=S().vehicles.find(v=>v.id===r.vehicleId);return `<button class="route-card ${selected===v.id?'selected':''}" data-action="route" data-id="${v.id}" style="--route-color:${v.color}" aria-label="查看${v.name}路线"><span class="top"><strong>${v.name}${v.wheelchair?' · 轮椅适配':''}</strong><span>${r.people} / ${v.capacity} 人</span></span><p>${r.stops.map(st=>esc(name(st.id))).join(' → ')}</p><small>送往 ${esc(name(r.shelterId))} · +${r.finish} 分抵达</small></button>`;}).join('')}${p.unassigned.length?`<div class="unassigned"><strong>${p.unassigned.length} 户仍待协调</strong>${p.unassigned.map(h=>`<p>${esc(h.name)} · ${h.people} 人<br>${esc(h.reason)}</p>`).join('')}</div>`:''}`;
    if(p)plans+=`<div class="plan-bottom">${D().confirmed?`${tag(locked()?'已冻结执行路线':p.complete?'已确认演练草案':'已确认可行部分','green')}<p class="hint">${D().confirmed.note?esc(D().confirmed.note):'方案确认不代表人员已转移。'}</p>${link('进入转移反馈 →','feedback','secondary full')}`:`${!p.complete?`<label class="checkbox"><input type="checkbox" id="partial-ack">我已知晓 ${p.unassigned.length} 户仍未安排</label><div class="field"><label for="partial-note">剩余家庭的协调措施</label><textarea id="partial-note" rows="2" maxlength="300" placeholder="例如：联系相邻片区增援车辆，保留未安排家庭待处理"></textarea></div>`:''}${b(p.complete?'人工确认当前草案':'确认可行部分','confirm','primary full',!p.servedPeople?'disabled':'')}<p class="hint">${p.complete?'请核对家庭与车辆安排。':'未安排家庭持续保留，不计作完成。'} 仅确认本地演练方案。</p>`}</div>`;
    return heading('AI 路径与调度','先满足接送约束，再比较分配与路线；每一项计算都可检查。',b(busy?'正在计算…':D().plan?'重新生成接送草案':'生成接送草案','generate','primary',locked()||busy?'disabled':''))+
      `<div class="stats">${stat('本次转移对象',total(),'人',S().households.length+' 户家庭 · 始终全量规划')}${stat('本方案覆盖',p?p.servedPeople:'—',p?'/ '+total()+' 人':'人',p?p.complete?'全部家庭有候选安排':p.unassigned.length+' 户仍需协调':'等待当前版本计算',true)}${stat('重点人员平均等待',p&&p.servedPeople?p.priorityAverage.toFixed(1):'—','分','按重点人员人数加权，到车到户为止')}${stat('预计最后抵达',p&&p.servedPeople?p.finish:'—','分','同时出发 · 包含行驶与接人')}</div>`+
      (locked()?'<div class="notice warning"><strong>已进入模拟执行，方案冻结。</strong> 本版仅支持出发前重规划。途中道路变化需要人工处置，不能用集结点起算方案替代。</div>':D().plan&&!fresh?`<div class="notice warning"><strong>输入已更新至 v${D().version}，原 v${D().planVersion} 草案不可确认。</strong> 人数、路况、资源与需求必须一致后重新计算。</div>`:'')+
      `<div class="event-toolbar"><span class="label">注入演练变化</span>${events.map(e=>`<button class="event-chip" data-action="event" data-id="${e[0]}" aria-pressed="${e[2]}" ${locked()||busy?'disabled':''}><span class="switch"></span>${e[1]}</button>`).join('')}</div>`+
      `<div class="dispatch-grid"><section class="panel">${head('接送路径','虚构路网示意，非真实地理位置；道路耗时为演练输入',tag(fresh?'方案 v'+D().planVersion:'等待计算',fresh?'blue':''))}<div class="map-tabs"><button class="map-tab ${selected==='all'?'active':''}" data-action="route" data-id="all">全部路线</button>${S().vehicles.map(v=>`<button class="map-tab ${selected===v.id?'active':''}" data-action="route" data-id="${v.id}"><i class="route-dot" style="background:${v.color}"></i>${v.name}</button>`).join('')}</div><div class="map-scroll">${mapSvg()}</div>${routeDetail()}</section><section class="panel plan-panel">${head('车辆接送安排','点击车辆，单独查看路线与接送顺序',tag(planLabel(),D().confirmed?'green':'blue'))}${plans}</section></div>`+
      (p?'<div class="constraint-strip section-gap">✓ 家庭不拆分 ✓ 车辆不超载 ✓ 轮椅位适配 ✓ 安置容量 ✓ 开放道路连续 ✓ 人数守恒</div>':'')+
      comparison()+`<div class="notice section-gap no-margin"><strong>能力说明：</strong> 路径与调度由本地算法实际计算。优先覆盖优先转移户、需协助户，再覆盖更多人；覆盖相同时减少重点等待，再减少最后抵达时间。当前未调用大模型，<a href="#evidence">查看能力与数据依据 →</a></div>`;
  }
  function receiptResult(){
    if(!draft)return '<span class="symbol">“</span><h3>“已通知”之后，还有什么困难？</h3><p>把回执整理成可核对的状态和协助需求，再决定是否更新接送条件。</p><p class="hint">当前为有限文本规则演示，大模型未接入。复杂否定、多人反馈需人工判断。</p>';
    const h=S().households.find(h=>h.id===draft.id);
    return `${tag(esc(draft.parsed.status),draft.parsed.unresolved?'orange':'blue')}<p>${esc(draft.parsed.summary)}</p><strong>${esc(h.name)} · ${h.people} 人</strong><label class="checkbox"><input id="checked-assistance" type="checkbox" ${draft.checked.assistance?'checked':''}>人工核实：需要上门协助</label><label class="checkbox"><input id="checked-wheelchair" type="checkbox" ${draft.checked.wheelchair?'checked':''}>人工核实：需要轮椅位</label>${b('核对后登记回执','apply-receipt','secondary')}<p class="hint">可修正规则建议。仅增加核实后的需求；取消既有需求请编辑台账。文本不会自动登记上车或核验到达。</p>`;
  }
  function feedback(){
    const p=store.fresh()?D().plan:null,counts={waiting:0,boarded:0,arrived:0,verified:0};for(const h of S().households)counts[D().execution[h.id]]+=h.people;
    const contactsReady=p&&p.routes.flatMap(r=>r.stops).every(st=>D().contact[st.id].contacted),ready=D().confirmed&&D().sent&&contactsReady;
    const gate=locked()?`<div class="notice success"><strong>模拟执行中 · 方案 v${D().planVersion} 已冻结</strong><p>按车辆接送顺序登记上车；本车接人完成后才能上报到达；人工核验与文字回执分开。${D().pending.length?'有 '+D().pending.length+' 项执行中新增需求待人工协调。':''}</p></div>`:
      `<div class="notice feedback-top"><div><strong>${D().confirmed?'方案已确认，等待启动模拟执行':'先核对并确认调度方案'}</strong><p>${!D().confirmed?'可先登记回执、核实需求，再进入路径与调度。':!D().sent?'请先在预警叫应页模拟发布任务。':!contactsReady?'已安排的家庭仍有未联系记录，请先完成逐户联系。':'本次已安排家庭均有联系记录，可以开始演练。'} ${D().confirmed&&!ready?'<a href="#warning">前往预警叫应 →</a>':''}</p></div>${D().confirmed?b('开始模拟执行','start','primary',!ready?'disabled':''):link('前往调度','dispatch','secondary')}</div>`;
    return heading('转移反馈','把现场说法、接送进展和人工核验分开，持续跟进没有解决的需求。',link('查看调度方案','dispatch','quiet'))+gate+
      `<div class="stats">${stat('本次转移对象',total(),'人','全量对象不随上报状态改变')}${stat('当前已上车',counts.boarded,'人','尚未登记到达安置点')}${stat('到达待核验',counts.arrived,'人','仅执行表中的到达登记')}${stat('已人工核验',counts.verified,'人','模拟核验，不代表真实人员安全',true)}</div>`+
      `<section class="panel">${head('接送进展','本表按钮模拟现场人员操作；文字回执不会推动本表状态',tag(locked()?'模拟执行中':'出发前准备',locked()?'green':''))}<div class="table-wrap"><table><thead><tr><th>家庭</th><th>接送安排</th><th>最近文字回执</th><th>执行记录</th><th>下一步操作</th></tr></thead><tbody>${S().households.map(h=>{const r=assigned(h.id),v=r?S().vehicles.find(v=>v.id===r.vehicleId):null,stage=D().execution[h.id];let action='';if(r&&locked()){const ix=r.stops.findIndex(st=>st.id===h.id),canBoard=!r.stops.slice(0,ix).some(st=>D().execution[st.id]==='waiting'),canArrive=!r.stops.some(st=>D().execution[st.id]==='waiting');action=stage==='waiting'?b('登记上车','board','secondary small',`data-id="${h.id}" ${!canBoard?'disabled':''} aria-label="${h.name}登记上车"`):stage==='boarded'?b('上报到达','arrive','secondary small',`data-id="${h.id}" ${!canArrive?'disabled':''} aria-label="${h.name}上报到达"`):stage==='arrived'?b('人工核验','verify','secondary small',`data-id="${h.id}" aria-label="${h.name}人工核验"`):tag('核验已登记','green');}else action='<span class="muted">'+(r?'等待开始演练':'等待协调安排')+'</span>';return `<tr><td>${home(h)}</td><td>${v?`<strong style="color:${v.color};font-weight:500">${v.name} · 第 ${r.stops.findIndex(st=>st.id===h.id)+1} 户</strong><small>${esc(name(r.shelterId))}</small>`:tag('待安排','orange')}</td><td>${esc(h.response)}</td><td>${tag(r?stageLabels[stage]:'未安排',stage==='verified'?'green':stage==='arrived'?'orange':'blue')}</td><td>${action}</td></tr>`;}).join('')}</tbody></table></div></section>`+
      (D().pending.length?`<div class="notice warning section-gap"><strong>执行中待协调事项</strong>${D().pending.map(x=>`<p>${esc(name(x.id))}：${esc(x.text)} · 已确认路线未自动更改</p>`).join('')}</div>`:'')+
      `<section class="panel section-gap">${head('回执整理与需求核实','规则演示 · 尚未接入大模型',tag('人工确认后登记','blue'))}<div class="feedback-grid"><div><div class="field"><label for="receipt-home">对应家庭</label><select id="receipt-home">${S().households.map(h=>`<option value="${h.id}" ${h.id===receiptHome?'selected':''}>${esc(h.name)} · ${h.people} 人</option>`).join('')}</select></div><div class="field"><label for="receipt-text">现场反馈原文</label><textarea id="receipt-text" maxlength="1000" rows="3">${esc(receiptText)}</textarea></div><div class="receipt-actions"><button class="text-button" data-action="sample">换一条示例</button>${b('整理回执','parse','secondary')}</div></div><div class="receipt-result" id="receipt-result">${receiptResult()}</div></div>${D().receipts.slice(0,3).map(r=>`<div class="receipt-log"><strong>${esc(name(r.id))} · 输入 v${r.version}</strong> ${tag(esc(r.parsed.status))}<br>原文：${esc(r.text)}</div>`).join('')}</section><div class="section-gap">${timeline(7)}</div>`;
  }
  function evidence(){
    const questions=[
      ['原“叫应”已有导航与回执，你们新增了什么？','继续围绕预警、受威胁家庭、包保责任和转移状态开展工作。本原型新增跨户车辆分配、接送顺序、轮椅和安置容量联合约束、出发前变化重算、同条件方案对比。原系统是否已有相似能力仍需访谈；当前是独立原型，没有原系统接口。'],
      ['AI 在哪里？是否只是给算法换了名字？','当前实际运行的是 Dijkstra 路径计算、约束下的候选组合搜索和有限文本规则。尚未实现大模型语义理解。下一步的模型模块应把自然语言回执、公开预案转为带依据的结构化建议，再调用调度工具，由人确认。页面明确保留这一区别。'],
      ['这些数据来自哪里？能否作为比赛数据？','本页所有家庭、角色、道路、分钟数、车辆和容量均为合成演练设定，可通过右上角导出 JSON 复现。原叫应场景依据公开报道。赛事手册要求数据集与知识库公开可获取；内部授权或脱敏不自动等于公开，合成数据参赛口径仍待组委会核实。'],
      ['为什么这样安排？是否牺牲重点家庭来追求速度？','硬约束先检查家庭不拆分、座位、轮椅位、开放道路与安置总容量。候选排序先覆盖优先转移户、需协助户，再覆盖人数；同覆盖下比较重点人群加权等待，随后比较最后抵达与行驶时间。优先级是演练设定，尚未经过应急专业人员确认，也不声称已证明全局最优。'],
      ['效率究竟比什么提高？如何避免挑选有利结果？','调度页在同一个输入快照上同时计算简单就近派车和联合调度。简单基线依优先级、家庭编号处理，为每户追加到可最早到户的可行车辆，不修改已选安置点。两方案都做相同约束校验。接送对象不同时禁止把时间差解释为同批人员效率提升，不预填提升百分比。'],
      ['车辆出发后桥断了，已上车的人会被重新派车吗？','本版只允许出发前重规划。开始模拟执行后冻结当前方案和计算输入，不能重算或修改道路资源；新增需求保留为待人工协调。执行表按接人顺序操作，未接完本车家庭不能到达登记；文字“收到”或“已到达”不自动确认转移完成。途中位置、在车人员约束与多趟接送是下一版必要工作。']
    ];
    return heading('方案依据','让评委看清业务价值、真实计算和仍需补足的证据。',b('导出输入、方案与记录','export','secondary'))+
      `<div class="evidence-intro"><span class="eyebrow">产品定位</span><h2>面向基层防汛的预警行动智能体</h2><p>保持“叫应”的应用场景：预警找到责任人，责任人联系到家庭，家庭获得具体行动安排。升级重点是把未解决的协助需求，转成可核对的接送与资源调度方案。</p></div>`+
      `<div class="capabilities"><article class="capability">${tag('已实现 · 本地计算','green')}<h3 class="section-gap">路线与联合调度</h3><p>开放道路最短路、跨户车辆分配、接送顺序、适配与容量校验、同输入基线、输入版本控制。</p></article><article class="capability">${tag('已实现 · 规则演示','blue')}<h3 class="section-gap">回执到需求字段</h3><p>保留原文、整理状态、提示协助与轮椅需求，人工修正后登记。文本不自动确认安全。</p></article><article class="capability">${tag('下一阶段 · 未接入','orange')}<h3 class="section-gap">真正的模型模块</h3><p>回执语义理解、公开预案检索、工具调用与依据追溯。需选择模型服务和可公开使用的数据。</p></article></div>`+
      `<section class="panel qa">${head('评审会追问的 6 个问题','把问题落到可检查的功能，而不是只写在介绍里')}${questions.map((q,i)=>`<details ${i===0?'open':''}><summary>${String(i+1).padStart(2,'0')}　${q[0]}</summary><p>${q[1]}</p></details>`).join('')}</section>`+
      `<div class="columns section-gap"><section class="panel">${head('现阶段的证据与来源','原产品事实和本队演练设定分别说明')}<div class="panel-body"><ul class="source-list"><li><a href="https://item.btime.com/43qb8qcv8098jsqi1od0gmoih04" target="_blank" rel="noreferrer">公开报道：密云“叫应”小程序</a>。作为业务场景参考；不代表与原开发方建立合作或接入。</li><li>用户提供《2026 联合国数据马拉松中国赛手册》：用于核对参赛要求，原件保存在项目目录。</li><li>虚构演练 v2：6 户家庭、16 个节点、22 条道路；所有耗时、角色、容量均是演练输入，可导出复现。</li><li>本版为非商业独立演示；原代码与素材的使用权需在后续合作中另行确认。</li></ul></div></section><section class="panel">${head('下一版最需要的材料','按对功能改进的影响排序')}<div class="panel-body"><ul class="compact-list"><li><strong>1. 一次实际工作流程</strong>谁发起、谁调度、谁确认、谁核验，特别是原程序已有的功能。</li><li><strong>2. 明确的业务规则</strong>优先顺序、同行人数、车辆适配、容量口径和道路核实方式。</li><li><strong>3. 一个可公开演示的真实区域</strong>可使用的路网、安置点、历史预警与道路中断信息。</li><li><strong>4. 模型与接口条件</strong>可调用的模型服务、评估样例，以及原系统开放接口的可能性。</li></ul></div></section></div>`;
  }
  function render(){
    const active=['warning','ledger','dispatch','feedback','evidence','assistant'];let hash=location.hash.slice(1);if(hash==='receipt-panel')hash='feedback';if(hash==='workspace')hash='dispatch';page=active.includes(hash)?hash:'warning';
    document.querySelectorAll('[data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
    $('context-people').textContent=`本次 ${S().households.length} 户 ${total()} 人`;$('context-version').textContent=`输入 v${D().version} · ${planLabel()}`;
    $('side-phase').textContent=locked()?'模拟执行中':D().confirmed?'已确认 · 待出发':'出发前准备';$('side-hint').textContent=locked()?'当前人员与路线冻结。现场新增需求转为待人工协调。':'预警到户，需求核实，方案确认后再开始模拟执行。';
    assistant.navigation(page);
    $('page').innerHTML=page==='assistant'?assistant.page():({warning,ledger,dispatch,feedback,evidence}[page])();
    if(partialDraft.version!==D().version||!D().plan)partialDraft={version:D().version,ack:false,note:''};
    if($('partial-ack'))$('partial-ack').checked=partialDraft.ack;
    if($('partial-note'))$('partial-note').value=partialDraft.note;
    if(page==='feedback')for(const item of D().pending)for(const action of ['board','arrive','verify']){const button=$('page').querySelector(`[data-action="${action}"][data-id="${item.id}"]`);if(button){button.disabled=true;button.textContent='新增需求待协调';button.title='该户进展已暂停；本版不支持途中变更车辆，需人工协调。';}}
    document.title=({warning:'预警叫应',ledger:'人员与资源',dispatch:'AI 路径与调度',feedback:'转移反馈',evidence:'方案依据',assistant:'AI 协同助手'}[page])+' · 叫应 AI';
  }
  async function generate(){if(busy)throw new Error('计算中，请稍候');if(locked())throw new Error('执行中路线已冻结，不支持途中重规划');busy=true;render();await new Promise(resolve=>setTimeout(resolve,30));try{const p=store.generate();selected='all';notify(`两种方案已计算：联合调度安排 ${p.servedPeople} 人${p.unassigned.length?'，'+p.unassigned.length+' 户待协调':''}`);return {status:p.complete?'draft':'partial',coveredPeople:p.servedPeople,version:D().version};}finally{busy=false;render();}}
  function openEdit(id,kind){
    if(locked())throw new Error('执行中不再修改已确认的输入');const item=kind==='households'?S().households.find(x=>x.id===id):S()[kind].find(x=>x.id===id);if(!item)throw new Error('对象不存在');
    const number=(id,label,val,min,max)=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="number" min="${min}" max="${max}" step="1" required value="${val}"></div>`;
    const content=kind==='households'?`<div class="form-row">${number('people','人数（含同行者）',item.people,1,50)}${number('service','接人用时（分钟）',item.service,0,120)}</div><div class="field"><label for="priority">转移优先级</label><select id="priority"><option value="1" ${item.priority===1?'selected':''}>常规接送</option><option value="2" ${item.priority===2?'selected':''}>需协助</option><option value="3" ${item.priority===3?'selected':''}>优先转移</option></select></div><label class="checkbox"><input type="checkbox" id="assistance" ${item.assistance?'checked':''}>需要上门协助</label><label class="checkbox"><input type="checkbox" id="wheelchair" ${item.wheelchair?'checked':''}>需要轮椅位</label><p class="hint">保存时，协助需求会同步到“需协助”或更高优先级；接人时间至少 5 分钟，轮椅至少 6 分钟。此为演练规则。</p>`:
      `${number('capacity',kind==='vehicles'?'总名额（人，含轮椅位）':'本次可接收人数',item.capacity,0,200)}<label class="checkbox"><input type="checkbox" id="available" ${item.available?'checked':''}>${kind==='vehicles'?'车辆可用':'安置点开放'}</label>${kind==='vehicles'?`<label class="checkbox"><input type="checkbox" id="wheelchair" ${item.wheelchair?'checked':''}>包含 1 个轮椅位</label>`:''}`;
    $('dialog-body').innerHTML=`<form id="edit-form" data-id="${id}" data-kind="${kind}"><div class="dialog-head"><h2>编辑${esc(item.name)}</h2><button class="button quiet small" type="button" data-action="close">关闭</button></div>${content}<p class="field-error" id="edit-error" role="alert"></p><div class="dialog-actions"><button class="button quiet" type="button" data-action="close">取消</button><button type="submit" class="button primary">保存修改</button></div></form>`;$('edit-dialog').showModal();
  }
  function exportExercise(){const blob=new Blob([JSON.stringify({...store.exportData(),assistant:assistant.serialize()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`叫应AI-虚构演练-v${D().version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('已导出演练输入、两种方案、回执、对话与操作记录');}
  document.addEventListener('submit',event=>{if(event.target.id!=='edit-form')return;event.preventDefault();try{if(busy)throw new Error('计算中请稍候');const form=event.target,id=form.dataset.id,kind=form.dataset.kind;const fields=kind==='households'?{people:Number($('people').value),service:Number($('service').value),priority:Number($('priority').value),assistance:$('assistance').checked,wheelchair:$('wheelchair').checked}:{capacity:Number($('capacity').value),available:$('available').checked,...(kind==='vehicles'?{wheelchair:$('wheelchair').checked}:{})};const changed=kind==='households'?store.updateHousehold(id,fields):store.updateResource(kind,id,fields);$('edit-dialog').close();render();notify(changed?'修改已保存，原方案需要重新计算':'内容没有变化，现有方案保持有效');}catch(error){$('edit-error').textContent=error.message;}});
  function clearDraft(){draft=null;if($('receipt-result'))$('receipt-result').innerHTML=receiptResult();}
  document.addEventListener('input',e=>{if(e.target.id==='receipt-text'){receiptText=e.target.value;clearDraft();}if(e.target.id==='partial-note')partialDraft.note=e.target.value;});
  document.addEventListener('change',e=>{if(e.target.id==='receipt-home'){receiptHome=e.target.value;clearDraft();}if(draft&&e.target.id==='checked-assistance')draft.checked.assistance=e.target.checked;if(draft&&e.target.id==='checked-wheelchair')draft.checked.wheelchair=e.target.checked;if(e.target.id==='partial-ack')partialDraft.ack=e.target.checked;});
  document.addEventListener('click',async event=>{
    const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const action=el.dataset.action,id=el.dataset.id;
    try{
      if(busy&&!['export','close'].includes(action))throw new Error('正在计算，请稍候');
      if(action==='generate'){await generate();return;}
      if(action==='route'){selected=id;render();return;}
      if(action==='edit-home'){openEdit(id,'households');return;}
      if(action==='edit-resource'){openEdit(id,el.dataset.kind);return;}
      if(action==='close'){$('edit-dialog').close();return;}
      if(action==='export'){exportExercise();return;}
      if(action==='parse'){const parsed=E.parseReceipt(receiptText);draft={id:receiptHome,text:receiptText,parsed,checked:{assistance:parsed.needsAssistance,wheelchair:parsed.needsWheelchair}};$('receipt-result').innerHTML=receiptResult();return;}
      if(action==='sample'){const samples=['收到。','已通知，需要轮椅车辆接送。','已到达安置点。','已通知，但家属还没到，需要人员陪同接送。'];receiptText=samples[sample++%samples.length];$('receipt-text').value=receiptText;clearDraft();return;}
      if(action==='apply-receipt'){if(!draft)throw new Error('输入已变化，请重新整理回执');const result=store.receipt(draft.id,draft.text,draft.checked);draft=null;notify(result.pending?'已登记为执行中待协调事项，该户接送记录已暂停':result.changed?'新增需求已保存，请重新规划':'回执已登记；接送进展未自动改变');}
      if(action==='publish'){store.publish();notify('演练任务已发布，请模拟逐户接收与联系');}
      if(action==='ack')store.acknowledge(id);
      if(action==='contact')store.contact(id);
      if(action==='event'){store.setEvent(id,el.getAttribute('aria-pressed')!=='true');notify('条件已更新，请重新计算两种方案');}
      if(action==='confirm'){if(!D().plan.complete&&!$('partial-ack')?.checked)throw new Error('请先确认知晓未安排家庭');store.confirm($('partial-note')?.value||'');notify('草案已人工确认；可进入转移反馈开始模拟执行');}
      if(action==='start'){store.start();notify('开始模拟执行，当前路线和计算输入已冻结');}
      if(['board','arrive','verify'].includes(action)){store.advance(id,action);notify(name(id)+'：'+stageLabels[D().execution[id]]);}
      if(action==='reset'){assistant.reset();store.reset();selected='all';draft=null;receiptHome='H5';receiptText='已通知，但家属还没到，需要人员陪同接送。';location.hash='warning';notify('已恢复初始演练，原浏览器内记录和对话已清空');}
      render();
    }catch(error){notify(error.message);}
  });
  window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
  function readState(){const d=D();return {version:d.version,page,phase:d.phase,modelMode:'finite-text-rules-no-llm',planState:!d.plan?'empty':!store.fresh()?'stale':d.confirmed?'confirmed':d.plan.complete?'draft':'partial',coveredPeople:store.fresh()?d.plan.servedPeople:null,totalPeople:total(),unassigned:store.fresh()?d.plan.unassigned.map(h=>({id:h.id,name:h.name,reason:h.reason})):[],baselineCovered:store.fresh()?d.baseline.servedPeople:null,execution:d.execution,pending:d.pending.length,events:{bridgeClosed:!S().edges.find(e=>e.id==='east').open,northClosed:!S().edges.find(e=>e.id==='north').open,shelterUnavailable:!S().shelters[1].available,vehicleUnavailable:!S().vehicles[1].available}};}
  render();
  const context=document.modelContext;
  if(context&&typeof context.registerTool==='function'){
    const lifecycle=new AbortController(),empty={type:'object',properties:{},additionalProperties:false};
    const noArgs=input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('不接受参数');};
    const tools=[{name:'read_exercise_state',title:'读取演练状态',description:'读取当前虚构演练输入版本、方案状态、基线覆盖与模拟执行记录。',inputSchema:empty,annotations:{readOnlyHint:true},execute(input){noArgs(input);return readState();}},
      {name:'generate_transfer_draft',title:'生成演练接送草案',description:'同时计算同一输入的联合调度和简单派车基线，仅出发前可用。',inputSchema:empty,annotations:{readOnlyHint:false},async execute(input){noArgs(input);return generate();}},
      {name:'set_exercise_event',title:'设置演练情景变化',description:'设置东桥或北桥封闭、体育馆暂停或2号车停用。仅出发前可用，会使原方案失效。',inputSchema:{type:'object',properties:{event:{type:'string',enum:['bridge','north','shelter','vehicle']},active:{type:'boolean'}},required:['event','active'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['event','active'].includes(k)))throw new Error('情景参数无效');if(busy)throw new Error('正在计算，请稍候');store.setEvent(input.event,input.active);render();return readState();}}];
    for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(_){}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
