/* Local previews only. The controller performs revision-checked submissions. */
(()=>{'use strict';
  const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const place=(data,r)=>{const v=data.villages.find(v=>v.id===r.villageId);return [v?.name||r.villageName||'村庄待明确',v?.pickups.find(p=>p.id===r.pickupId)?.name||r.pickupName||'集合点待补'].join(' · ');};
  function command(state,ui,h){
    const p=ui.draft,rows=p?.rows||[],stale=p&&(p.revision!==state.data.revision||p.session!==state.session),total=rows.reduce((n,r)=>n+r.people,0),blocked=ui.busy||ui.voiceActive||!ui.connected||!state.capabilities.commandIntake;
    const hasMissing=rows.some(r=>r.assistancePeople==null||r.wheelchairPeople==null||r.groupPolicy==='unknown');
    const located=r=>!!(r.locationNodeId||state.data.villages.find(v=>v.id===r.villageId)?.pickups.find(p=>p.id===r.pickupId)?.node);
    const missing=r=>[!located(r)&&!(Number.isFinite(r.longitude)&&Number.isFinite(r.latitude))?'地图位置':null,r.assistancePeople==null?'协助人数':null,r.wheelchairPeople==null?'轮椅人数':null,r.groupPolicy==='unknown'?'同行关系':null].filter(Boolean);
    const number=(r,i,key,label)=>`<input class="intake-count" type="number" min="0" max="${r.people}" value="${r[key]??''}" placeholder="未确认" aria-label="第${i+1}条${label}" data-intake-field="${key}" data-row="${i}" ${blocked?'disabled':''}>`;
    const materials=`<div class="intake-upload"><strong>Excel / CSV 人员需求</strong><p>每人一行或按村汇总，最多 100 条。可带 WGS84 经度、纬度；不要求逐人点击。</p><div class="actions"><label class="file-button" for="intake-file">上传需求名单<input id="intake-file" type="file" accept=".xlsx,.csv" ${blocked||ui.reading?'disabled':''}></label><button data-ac="intake-template" class="quiet" ${ui.reading?'disabled':''}>下载带定位列的模板</button></div><p role="status">${e(ui.reading?'正在整理上传需求…':ui.filename||'文件只在当前浏览器读取，不上传到 GitHub。')}</p></div>
      <details class="compact-disclosure" id="intake-speech" ${ui.source==='voice'||ui.text?'open':''}><summary><strong>语音 / 文字录入</strong><span> · 说一句，或粘贴多村需求</span></summary><label for="intake-text">说清位置与人数</label><textarea id="intake-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="例如：演示村 A 新增 6 人，其中 1 人需要协助，无轮椅，可以分组。">${e(ui.text)}</textarea>${h.voiceHTML('command-intake')}<div class="actions">${h.btn('整理需求','intake-parse',blocked?'disabled':'','primary')}${h.btn('填入演示示例','intake-example',blocked?'disabled':'','quiet')}</div></details>`;
    return `<section class="panel intake-panel" id="command-intake"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">＋</span><div><span class="eyebrow">01 提供需求 · 02 核对内容 · 03 导入需求</span><h2>先提供需求，再核对</h2><p>上传名单，或用语音 / 文字说明；整理后核对人数和位置，再导入需求。</p></div></div><div class="panel-body">
      ${p?`<details class="compact-disclosure intake-materials" id="intake-materials"><summary>更换材料 / 修改原话</summary>${materials}</details>`:materials}
      ${p?`<div class="intake-review" id="intake-review" role="region" aria-label="批量任务核对"><div class="close-row"><h3>核对 ${rows.length} 条需求 · ${total} 人</h3>${h.badge('待导入预览','teal')}</div>${p.errors.length?`<div class="notice warn"><strong>请修正以下行，本批尚未写入</strong>${p.errors.map(x=>`<p>${e(x)}</p>`).join('')}</div>`:''}
      ${rows.length?`<p class="boundary">空白表示未确认，不会按 0 人处理；可以先导入，待信息补齐后再安排接送。地图用橙色标记可定位的预览。</p><div class="table-wrap"><table class="intake-preview-table"><thead><tr><th>村庄 / 接人点</th><th>人数</th><th>协助 / 轮椅</th><th>分组</th><th>位置</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><strong>${e(place(state.data,r))}</strong><small>名单第 ${r.rowIndex||i+1} 行</small>${missing(r).length?`<small class="intake-missing">待补：${missing(r).map(e).join('、')}</small>`:''}</td><td>${r.people}</td><td>${number(r,i,'assistancePeople','需协助人数')} / ${number(r,i,'wheelchairPeople','轮椅人数')}</td><td><select data-intake-field="groupPolicy" data-row="${i}" aria-label="第${i+1}条分组方式" ${blocked?'disabled':''}>${[['unknown','待补'],['splittable','可分组'],['together','须同行']].map(([v,t])=>`<option value="${v}" ${r.groupPolicy===v?'selected':''}>${t}</option>`).join('')}</select></td><td><small>${located(r)?'已有接入点':Number.isFinite(r.longitude)&&Number.isFinite(r.latitude)?'有坐标 · 待匹配道路':'待定位'}</small>${h.btn('地图选点','map-locate-draft',`data-id="${i}" ${blocked?'disabled':''}`,'small quiet')}</td></tr>`).join('')}</tbody></table></div>`:''}
      ${hasMissing?`<div class="notice"><strong>一批需求采用相同条件？</strong><p>如已确认剩余未填项均无特殊需求且可以分组，可一次补齐；已有数值保持。已填轮椅人数的行需要单独明确协助人数。</p>${h.btn('未填项设为：协助 0、轮椅 0、可分组','intake-bulk-standard',blocked?'disabled':'','small')}</div>`:''}
      ${p.warnings.length?`<details class="compact-disclosure"><summary>查看整理提示（${p.warnings.length}）</summary><p>${p.warnings.map(e).join('；')}</p></details>`:''}
      <p id="intake-field-errors" class="error-text" role="alert"></p>${ui.duplicates?`<label class="check notice warn"><input id="intake-duplicate" type="checkbox" ${ui.duplicateAcknowledged?'checked':''}>相似记录属于另一批人员，仍需新增。</label>`:''}${stale?'<div class="notice warn">现场数据有更新，请重新核对；已补的位置和人数会保留。</div>':''}<div class="actions">${h.btn(stale?'按最新数据重新核对':'导入需求并查看路线',stale?'intake-refresh':'intake-submit',blocked||!rows.length||p.errors.length||(!stale&&ui.duplicates&&!ui.duplicateAcknowledged)?'disabled':'','primary')}${h.btn('撤回草稿','intake-clear',blocked?'disabled':'','quiet')}</div></div>`:''}
      <p class="boundary">人数、容量和路线由系统检查。导入后查看安排，点击发布，无需手输确认文字。当前为本地规则整理。</p></div></section>`;
  }
  function quick(state,ui,h){const p=ui.draft,payload=p?.proposal?.payload,stale=p&&(p.revision!==state.data.revision||p.session!==state.session),disabled=ui.busy||ui.voiceActive||!ui.connected;
    return `<section class="panel quick-capture" id="quick-capture"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">声</span><div><span class="eyebrow">现场补充 · 少点几下</span><h2>发现新增人员？直接说</h2><p>例如“这里又发现 3 人，其中 1 人需要协助”。</p></div></div><div class="panel-body"><div class="quick-scope"><strong>${e(ui.scope.label||'请在原话中说出村庄')}</strong><small>${ui.scope.source==='task'?'已带入当前车辆的下一接送点':ui.scope.source==='selection'?'沿用您选择的位置':'也可展开下方位置设置，选一次后继续沿用'}</small></div><details class="compact-disclosure" id="quick-scope-options"><summary>切换村庄 / 集合点</summary><div class="form-grid"><label>村庄<select id="quick-village" ${ui.voiceActive?'disabled':''}><option value="">跟随当前任务</option>${state.data.villages.map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.villageId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label><label>集合点<select id="quick-pickup" ${ui.voiceActive?'disabled':''}><option value="">稍后补充</option>${(state.data.villages.find(v=>v.id===ui.scope.villageId)?.pickups||[]).map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.pickupId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label></div></details><label for="quick-text">语音或文字补报</label><textarea id="quick-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="这里又发现 3 人，其中 1 人需要协助。">${e(ui.text)}</textarea>${h.voiceHTML('quick')}<div class="actions">${h.btn('整理补报','quick-parse',disabled?'disabled':'','primary')}${h.btn('清空','quick-clear',disabled?'disabled':'','quiet')}</div><p class="boundary">一次说出一批人数，不必逐人录入。未说清的需求保留为待补。</p>${p?`<div class="quick-review" id="quick-review"><h3>${payload?`待确认：新增 ${payload.people} 人`:'请补充一句'}</h3>${payload?`<strong>${e(place(state.data,payload))}</strong><p>需协助 ${payload.assistancePeople??'待补'} 人 · 轮椅 ${payload.wheelchairPeople??'待补'} 人 · ${e({splittable:'可分组',together:'须同行',unknown:'同行关系待补'}[payload.groupPolicy])}</p>`:''}<blockquote>${e(ui.text)}</blockquote>${(p.questions||[]).map(q=>`<p class="notice warn">${e(q)}</p>`).join('')}${(p.warnings||[]).length?`<p class="boundary">${p.warnings.map(e).join('；')}</p>`:''}${ui.duplicate?`<label class="check notice warn"><input id="quick-duplicate" type="checkbox" ${payload?.duplicateAcknowledged?'checked':''}>已核对相似补报，这批是另外新增人员。</label>`:''}${stale?'<p class="notice warn">任务已更新，请重新整理后核对。</p>':''}${payload?h.btn(stale?'按最新任务重新整理':`确认补报 ${payload.people} 人`,stale?'quick-parse':'quick-submit',disabled||(!stale&&ui.duplicate&&!payload.duplicateAcknowledged)?'disabled':'','primary quick-confirm'):''}</div>`:''}${ui.receipt?`<div class="notice field-receipt" role="status"><strong>✓ ${e(ui.receipt)}</strong><p>已送达指挥台，等待核实后纳入安排。</p></div>`:''}</div></section>`;
  }
  window.JiaoyingIntakeUI={command,quick};
})();
