/* Local previews only. The controller performs revision-checked submissions. */
(()=>{'use strict';
  const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const place=(data,r)=>{const v=data.villages.find(v=>v.id===r.villageId);return [v?.name||'村庄待明确',v?.pickups.find(p=>p.id===r.pickupId)?.name||'集合点待补'].join(' · ');};
  const missing=r=>[!r.pickupId?'集合点':null,r.assistancePeople==null?'协助人数':null,r.wheelchairPeople==null?'轮椅人数':null,r.groupPolicy==='unknown'?'同行关系':null].filter(Boolean);
  function command(state,ui,h){const p=ui.draft,rows=p?.rows||[],stale=p&&(p.revision!==state.data.revision||p.session!==state.session),total=rows.reduce((n,r)=>n+r.people,0),blocked=ui.busy||ui.voiceActive||!ui.connected||!state.capabilities.commandIntake;
    return `<section class="panel intake-panel" id="command-intake"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">＋</span><div><span class="eyebrow">指挥发起 · 一次整理多条需求</span><h2>快捷建任务</h2><p>导入人员名单，或说出哪个村、哪里集合、有多少人。</p></div></div><div class="panel-body"><div class="intake-input-layout"><div><label for="intake-text">说一句，或粘贴多条转移需求</label><textarea id="intake-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="例如：演示村 A 新增 6 人，其中 1 人需要协助。可连续描述多个村。">${e(ui.text)}</textarea>${h.voiceHTML('command-intake')}<div class="actions">${h.btn('整理为任务草稿','intake-parse',blocked?'disabled':'','primary')}${h.btn('填入演示示例','intake-example',blocked?'disabled':'','quiet')}</div></div><div class="intake-upload"><strong>已有名单？一次导入</strong><p>Excel .xlsx / CSV · 最多 100 条需求<br>每人一行或按村汇总人数均可。</p><label class="file-button" for="intake-file">选择人员名单<input id="intake-file" type="file" accept=".xlsx,.csv" ${blocked||ui.reading?'disabled':''}></label><button data-ac="intake-template" class="quiet" ${ui.reading?'disabled':''}>下载 CSV 模板</button><p role="status">${e(ui.reading?'正在读取名单…':ui.filename||'文件在当前浏览器读取，只保存核对后的任务字段。')}</p><small>模板包含当前演练村庄和集合点。未知村庄、格式错误会列出原行号；整批核对后才写入。</small></div></div><p class="boundary">当前由本地规则整理，未接入大模型。建任务后核对路线，再确认模拟发布。</p>${!state.capabilities.commandIntake?'<div class="notice warn">当前本地服务需要更新到 V3.7 才能批量建任务；也可使用新版 GitHub 网页。</div>':''}${p?`<div class="intake-review" id="intake-review" role="region" aria-label="批量任务核对"><div class="close-row"><h3>核对 ${rows.length} 条需求 · ${total} 人</h3>${h.badge(ui.source==='file'?'名单整理':ui.source==='voice'?'语音整理':'文字整理','teal')}</div>${p.errors.length?`<div class="notice warn"><strong>先修正以下问题，本次尚未写入任何任务</strong>${p.errors.map(x=>`<p>${e(x)}</p>`).join('')}</div>`:''}${p.warnings.length?`<p class="boundary">${p.warnings.map(e).join('；')}</p>`:''}${rows.length?`<div class="table-wrap"><table><thead><tr><th>来源行</th><th>村庄 / 集合点</th><th>新增人数</th><th>协助 / 轮椅</th><th>同行关系</th><th>准备情况</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.rowIndex||'—')}</td><td>${e(place(state.data,r))}</td><td><strong>${r.people}</strong></td><td>${r.assistancePeople??'待补'} / ${r.wheelchairPeople??'待补'}</td><td>${e({splittable:'可分组',together:'须同行',unknown:'待补'}[r.groupPolicy])}</td><td>${missing(r).length?'待补 '+missing(r).join('、'):'可生成接送组'}</td></tr>`).join('')}</tbody></table></div><p class="boundary">缺少接送信息的需求先进入台账，待补齐后参加路线计算。导入不会覆盖原任务。</p>`:''}${ui.duplicates?`<label class="check notice warn"><input id="intake-duplicate" type="checkbox" ${ui.duplicateAcknowledged?'checked':''}>发现同村、同集合点、同人数的相似记录。我已确认这些行属于不同人员，仍需新增。</label>`:''}${stale?'<div class="notice warn">两端数据已变化，请重新整理并核对这批需求。</div>':''}<div class="actions">${h.btn(stale?'按最新数据重新核对':'确认这批需求并生成安排',stale?'intake-refresh':'intake-submit',blocked||!rows.length||p.errors.length||(!stale&&ui.duplicates&&!ui.duplicateAcknowledged)?'disabled':'','primary')}${h.btn('撤回这份草稿','intake-clear',blocked?'disabled':'','quiet')}</div></div>`:''}</div></section>`;
  }
  function quick(state,ui,h){const p=ui.draft,payload=p?.proposal?.payload,stale=p&&(p.revision!==state.data.revision||p.session!==state.session),disabled=ui.busy||ui.voiceActive||!ui.connected;
    return `<section class="panel quick-capture" id="quick-capture"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">声</span><div><span class="eyebrow">现场补充 · 少点几下</span><h2>发现新增人员？直接说</h2><p>例如“这里又发现 3 人，其中 1 人需要协助”。</p></div></div><div class="panel-body"><div class="quick-scope"><strong>${e(ui.scope.label||'请在原话中说出村庄')}</strong><small>${ui.scope.source==='task'?'已带入当前车辆的下一接送点':ui.scope.source==='selection'?'沿用您选择的位置':'也可展开下方位置设置，选一次后继续沿用'}</small></div><details class="compact-disclosure" id="quick-scope-options"><summary>切换村庄 / 集合点</summary><div class="form-grid"><label>村庄<select id="quick-village" ${ui.voiceActive?'disabled':''}><option value="">跟随当前任务</option>${state.data.villages.map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.villageId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label><label>集合点<select id="quick-pickup" ${ui.voiceActive?'disabled':''}><option value="">稍后补充</option>${(state.data.villages.find(v=>v.id===ui.scope.villageId)?.pickups||[]).map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.pickupId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label></div></details><label for="quick-text">语音或文字补报</label><textarea id="quick-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="这里又发现 3 人，其中 1 人需要协助。">${e(ui.text)}</textarea>${h.voiceHTML('quick')}<div class="actions">${h.btn('整理补报','quick-parse',disabled?'disabled':'','primary')}${h.btn('清空','quick-clear',disabled?'disabled':'','quiet')}</div><p class="boundary">一次说出一批人数，不必逐人录入。未说清的需求保留为待补。</p>${p?`<div class="quick-review" id="quick-review"><h3>${payload?`待确认：新增 ${payload.people} 人`:'请补充一句'}</h3>${payload?`<strong>${e(place(state.data,payload))}</strong><p>需协助 ${payload.assistancePeople??'待补'} 人 · 轮椅 ${payload.wheelchairPeople??'待补'} 人 · ${e({splittable:'可分组',together:'须同行',unknown:'同行关系待补'}[payload.groupPolicy])}</p>`:''}<blockquote>${e(ui.text)}</blockquote>${(p.questions||[]).map(q=>`<p class="notice warn">${e(q)}</p>`).join('')}${(p.warnings||[]).length?`<p class="boundary">${p.warnings.map(e).join('；')}</p>`:''}${ui.duplicate?`<label class="check notice warn"><input id="quick-duplicate" type="checkbox" ${payload?.duplicateAcknowledged?'checked':''}>已核对相似补报，这批是另外新增人员。</label>`:''}${stale?'<p class="notice warn">任务已更新，请重新整理后核对。</p>':''}${payload?h.btn(stale?'按最新任务重新整理':`确认补报 ${payload.people} 人`,stale?'quick-parse':'quick-submit',disabled||(!stale&&ui.duplicate&&!payload.duplicateAcknowledged)?'disabled':'','primary quick-confirm'):''}</div>`:''}${ui.receipt?`<div class="notice field-receipt" role="status"><strong>✓ ${e(ui.receipt)}</strong><p>已送达指挥台，等待核实后纳入安排。</p></div>`:''}</div></section>`;
  }
  window.JiaoyingIntakeUI={command,quick};
})();
