/* Local previews only. The controller performs revision-checked submissions. */
(()=>{'use strict';
  const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const place=(data,r)=>{const v=data.villages.find(v=>v.id===r.villageId);return [v?.name||r.villageName||'村庄待明确',v?.pickups.find(p=>p.id===r.pickupId)?.name||r.pickupName||'集合点待补'].join(' · ');};
  function command(state,ui,h){
    const p=ui.draft,model=window.JiaoyingCommandIntake?.summary(state,p?.rows||[]),rows=model?.rows||p?.rows||[],stale=p&&(p.revision!==state.data.revision||p.session!==state.session),total=model?.incomingPeople||0,blocked=ui.busy||ui.voiceActive||!ui.connected||!state.capabilities.commandIntake;
    const hasMissing=rows.some(r=>r.assistancePeople==null||r.wheelchairPeople==null||r.groupPolicy==='unknown');
    const number=(r,i,key,label)=>`<input class="intake-count ${key==='people'?'intake-total':''}" type="number" min="${key==='people'?1:0}" max="${key==='people'?500:r.people}" value="${r[key]??''}" placeholder="未确认" aria-label="第${i+1}条${label}" data-intake-field="${key}" data-row="${i}" ${blocked?'disabled':''}>`;
    const picker=(id,label,value,options,attributes={})=>window.JiaoyingEntryKit?window.JiaoyingEntryKit.pickerHTML({id,label,value,options,attributes,disabled:blocked,placeholder:'搜索或手动填写'}):`<label>${label}<input id="${id}" value="${e(value||'')}" ${Object.entries(attributes).map(([k,v])=>`${k}="${e(v)}"`).join(' ')} ${blocked?'disabled':''}></label>`;
    const directory=window.JiaoyingPlaceDirectory;
    const villageOptions=directory.villageOptions(state.data,ui.scope?.villageId);
    const name=(r,i,key,label)=>picker('intake-'+key+'-'+i,'第'+(i+1)+'条'+label,r[key]||'',key==='villageName'?directory.villageOptions(state.data,r.villageId):directory.pickupOptions(state.data,r.villageId),{'data-intake-field':key,'data-row':i});
    const grouping=x=>({unknown:'待补',splittable:'可分组',together:'须同行'}[x]||'待补');
    const method=ui.method||((ui.source==='file'||ui.filename)?'file':ui.text?'text':'quick'),scope=ui.scope||{},fast=ui.fast||{};
    const scopeHTML=`<div class="intake-place-grid">${picker('intake-scope-village','地区 / 村庄',scope.villageName,villageOptions,{'data-intake-scope':'villageName'})}${picker('intake-scope-pickup','具体接人点',scope.pickupName,directory.pickupOptions(state.data,scope.villageId),{'data-intake-scope':'pickupName'})}</div><p class="boundary">${directory.isRoad(state.data)?'当前使用瑞安真实地名目录。搜索街道、社区或村名，再选择具体接人点；城区道路候选不代表已核实的辖区归属或安全集合点。':'本场仍是示意演练，地点目录沿用原记录。切换下方瑞安道路任务后即可选择真实地名。'}新地点也可手动填写，先保存、再地图定位。</p>`;
    const fastNumber=(key,label,min)=>`<label>${label}<input id="intake-fast-${key}" data-intake-fast="${key}" type="number" min="${min}" max="500" value="${e(fast[key]??'')}" placeholder="${key==='people'?'填写人数':'未确认可留空'}" ${blocked?'disabled':''}></label>`;
    const materials=`${window.JiaoyingEntryKit.modesHTML({label:'需求录入方式',value:method,disabled:blocked,className:'intake-methods',items:[['quick','选地点填人数'],['text','语音 / 文字'],['file','Excel 导入']].map(([value,label])=>({value,label,attributes:{'data-ac':'intake-method-'+value}}))})}
      ${method==='file'?window.JiaoyingEntryKit.fileHTML({id:'intake-file',label:'上传需求名单',description:'每人一行或按村汇总，最多 100 条。可带 WGS84 经度、纬度；不要求逐人点击。',templateAction:'intake-template',templateLabel:'下载需求 Excel 模板',status:ui.reading?'正在整理上传需求…':ui.filename||'文件只在当前浏览器读取，不上传到 GitHub。',disabled:blocked||ui.reading}):method==='quick'?`<div class="intake-fast">${scopeHTML}<div class="intake-fast-count">${fastNumber('people','新增人数（必填）',1)}</div><details class="compact-disclosure"><summary>协助与同行情况 · 已知时填写</summary><div class="form-grid">${fastNumber('assistancePeople','需协助人数',0)}${fastNumber('wheelchairPeople','其中轮椅人数',0)}<label>同行关系<select id="intake-fast-groupPolicy" data-intake-fast="groupPolicy" ${blocked?'disabled':''}>${[['unknown','尚未确认'],['splittable','可分组'],['together','须同行']].map(([v,l])=>`<option value="${v}" ${(fast.groupPolicy||'unknown')===v?'selected':''}>${l}</option>`).join('')}</select></label></div></details><div class="actions">${h.btn('下一步：核对这批需求','intake-fast-prepare',blocked?'disabled':'','primary')}</div></div>`:`<div class="intake-text-entry">${scopeHTML}<label for="intake-text">说出新增人数与情况（已选地点可以不重复说）</label><textarea id="intake-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="例如：玉海街道，新增 10 人，其中 2 人需协助。">${e(ui.text)}</textarea>${h.voiceHTML('command-intake')}<div class="actions">${h.btn('整理需求','intake-parse',blocked?'disabled':'','primary')}${h.btn('填入演示示例','intake-example',blocked?'disabled':'','quiet')}</div></div>`}`;
    const errors=[...(p?.errors||[]),...(model?.errors||[])],warnings=[...new Set([...(p?.warnings||[]),...(model?.warnings||[])])];
    return `<section class="panel intake-panel" id="command-intake"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">＋</span><div><span class="eyebrow">01 提供需求 · 02 一页核对 · 03 保存需求</span><h2>选地点、填人数，快速录入需求</h2><p>下拉选择或搜索地点，也可使用语音和名单；整理后在一张表核对。</p></div></div><div class="panel-body">
      ${!directory.isRoad(state.data)?`<div class="notice"><strong>当前地点：示意演练目录</strong><p>瑞安底图仅用于浏览。${state.mapConversion?.allowed===false?'本场已有保存记录，结束后可新建瑞安道路任务。':'启用瑞安道路后，这里的地点列表会同步切换。'}</p>${h.btn(state.mapConversion?.allowed===false?'结束本场，再换地图':'启用瑞安道路',state.mapConversion?.allowed===false?'end-for-road-dialog':'map-enable',blocked?'disabled':'','quiet small')}</div>`:''}
      ${p?`<details class="compact-disclosure intake-materials" id="intake-materials"><summary>更换材料 / 修改原话</summary>${materials}</details>`:materials}
      ${p?`<div class="intake-review" id="intake-review" role="region" aria-label="批量任务核对"><div class="close-row"><h3>核对 ${rows.length} 条需求 · ${total} 人</h3>${h.badge('待导入预览','teal')}</div><div class="notice intake-summary"><strong>本场已有 ${model?.existingPeople||0} 人 ＋ 此次新增 ${total} 人 ＝ 保存后 ${model?.afterPeople||0} 人</strong><p>这是新增一批需求，不会覆盖已有人员。${model?.pendingReportPeople?`另有现场补报 ${model.pendingReportPeople} 人待核实，未计入上述总数。`:''}</p></div>
      ${errors.length?`<div class="notice warn"><strong>请修正以下行，本批尚未写入</strong>${[...new Set(errors)].map(x=>`<p>${e(x)}</p>`).join('')}</div>`:''}
      ${rows.length?`<div class="notice intake-ready"><strong>信息齐全 ${model?.readyPeople||0} 人 · 待补 / 待定位 ${model?.pendingPeople||0} 人</strong><p>信息齐全的需求可进入排程；实际能安排多少人，仍取决于车辆、容量和道路。空白表示未确认，不会当作 0 人。</p></div><div class="table-wrap"><table class="intake-preview-table"><thead><tr><th>地区 / 接人点（可搜索、可填写）</th><th>人数</th><th>协助 / 轮椅</th><th>分组</th><th>位置 / 缺项</th></tr></thead><tbody>${rows.map((r,i)=>{const village=state.data.villages.find(v=>v.id===r.villageId),review=r.review||{},original=r.original||r;return `<tr><td>${name(r,i,'villageName','地区 / 村庄')}${name(r,i,'pickupName','接人点')}<small>需求第 ${i+1} 条${r.editedFields?.length?' · 已人工修改':''}</small>${r.editedFields?.length?`<details class="intake-original"><summary>查看原值</summary><small>${e(original.villageName||'村庄待补')} · ${e(original.pickupName||'接人点待补')}<br>人数 ${e(original.people??'待补')}；协助 ${e(original.assistancePeople??'待补')}；轮椅 ${e(original.wheelchairPeople??'待补')}；${grouping(original.groupPolicy)}</small></details>`:''}</td><td>${number(r,i,'people','新增人数')}</td><td>${number(r,i,'assistancePeople','需协助人数')} / ${number(r,i,'wheelchairPeople','轮椅人数')}</td><td><select data-intake-field="groupPolicy" data-row="${i}" aria-label="第${i+1}条分组方式" ${blocked?'disabled':''}>${[['unknown','待补'],['splittable','可分组'],['together','须同行']].map(([v,t])=>`<option value="${v}" ${r.groupPolicy===v?'selected':''}>${t}</option>`).join('')}</select></td><td><small>${e(review.location?.label||'待定位')}</small>${review.missing?.length?`<small class="intake-missing">待补：${review.missing.map(e).join('、')}</small>`:''}${h.btn('地图选点','map-locate-draft',`data-id="${i}" ${blocked?'disabled':''}`,'small quiet')}</td></tr>`;}).join('')}</tbody></table></div>`:''}
      ${hasMissing?`<details class="compact-disclosure"><summary>批量补齐相同条件</summary><p>只有已确认所有未填项均无特殊需求、可以分组时，才使用此按钮。已有数值保持；已填轮椅人数但未知协助人数的行仍需核对。</p>${h.btn('已确认：未填项均为协助 0、轮椅 0、可分组','intake-bulk-standard',blocked?'disabled':'','small')}</details>`:''}
      ${warnings.length?`<details class="compact-disclosure"><summary>位置与整理说明（${warnings.length}）</summary><p>${warnings.map(e).join('；')}</p></details>`:''}
      <p id="intake-field-errors" class="error-text" role="alert"></p>${ui.duplicates?`<label class="check notice warn"><input id="intake-duplicate" type="checkbox" ${ui.duplicateAcknowledged?'checked':''}>相似记录属于另一批人员，仍需新增。</label>`:''}${stale?'<div class="notice warn">现场数据有更新，请重新核对；已补的位置和人数会保留。</div>':''}<div class="actions">${h.btn(stale?'按最新数据重新核对':model?.pendingRows?'保存需求并补齐信息':'保存需求并查看安排',stale?'intake-refresh':'intake-submit',blocked||!rows.length||errors.length||(!stale&&ui.duplicates&&!ui.duplicateAcknowledged)?'disabled':'','primary')}${h.btn('撤回草稿','intake-clear',blocked?'disabled':'','quiet')}</div></div>`:''}
      <p class="boundary">保存不等于发布。需求核对后，前往任务执行查看安排并点击发布，无需手输确认文字。当前为本地规则整理。</p></div></section>`;
  }
  function quick(state,ui,h){const p=ui.draft,payload=p?.proposal?.payload,stale=p&&(p.revision!==state.data.revision||p.session!==state.session),disabled=ui.busy||ui.voiceActive||!ui.connected;
    return `<section class="panel quick-capture" id="quick-capture"><div class="intake-heading"><span class="intake-icon" aria-hidden="true">声</span><div><span class="eyebrow">现场补充 · 少点几下</span><h2>发现新增人员？直接说</h2><p>例如“这里又发现 3 人，其中 1 人需要协助”。</p></div></div><div class="panel-body"><div class="quick-scope"><strong>${e(ui.scope.label||'请在原话中说出村庄')}</strong><small>${ui.scope.source==='task'?'已带入当前车辆的下一接送点':ui.scope.source==='selection'?'沿用您选择的位置':'也可展开下方位置设置，选一次后继续沿用'}</small></div><details class="compact-disclosure" id="quick-scope-options"><summary>切换村庄 / 集合点</summary><div class="form-grid"><label>村庄<select id="quick-village" ${ui.voiceActive?'disabled':''}><option value="">跟随当前任务</option>${window.JiaoyingPlaceDirectory.villages(state.data,ui.scope.villageId).map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.villageId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label><label>集合点<select id="quick-pickup" ${ui.voiceActive?'disabled':''}><option value="">稍后补充</option>${(state.data.villages.find(v=>v.id===ui.scope.villageId)?.pickups||[]).map(v=>`<option value="${e(v.id)}" ${v.id===ui.scope.pickupId?'selected':''}>${e(v.name)}</option>`).join('')}</select></label></div></details><label for="quick-text">语音或文字补报</label><textarea id="quick-text" maxlength="2000" ${ui.voiceActive?'readonly':''} placeholder="这里又发现 3 人，其中 1 人需要协助。">${e(ui.text)}</textarea>${h.voiceHTML('quick')}<div class="actions">${h.btn('整理补报','quick-parse',disabled?'disabled':'','primary')}${h.btn('清空','quick-clear',disabled?'disabled':'','quiet')}</div><p class="boundary">一次说出一批人数，不必逐人录入。未说清的需求保留为待补。</p>${p?`<div class="quick-review" id="quick-review"><h3>${payload?`待确认：新增 ${payload.people} 人`:'请补充一句'}</h3>${payload?`<strong>${e(place(state.data,payload))}</strong><p>需协助 ${payload.assistancePeople??'待补'} 人 · 轮椅 ${payload.wheelchairPeople??'待补'} 人 · ${e({splittable:'可分组',together:'须同行',unknown:'同行关系待补'}[payload.groupPolicy])}</p>`:''}<blockquote>${e(ui.text)}</blockquote>${(p.questions||[]).map(q=>`<p class="notice warn">${e(q)}</p>`).join('')}${(p.warnings||[]).length?`<p class="boundary">${p.warnings.map(e).join('；')}</p>`:''}${ui.duplicate?`<label class="check notice warn"><input id="quick-duplicate" type="checkbox" ${payload?.duplicateAcknowledged?'checked':''}>已核对相似补报，这批是另外新增人员。</label>`:''}${stale?'<p class="notice warn">任务已更新，请重新整理后核对。</p>':''}${payload?h.btn(stale?'按最新任务重新整理':`确认补报 ${payload.people} 人`,stale?'quick-parse':'quick-submit',disabled||(!stale&&ui.duplicate&&!payload.duplicateAcknowledged)?'disabled':'','primary quick-confirm'):''}</div>`:''}${ui.receipt?`<div class="notice field-receipt" role="status"><strong>✓ ${e(ui.receipt)}</strong><p>已送达指挥台，等待核实后纳入安排。</p></div>`:''}</div></section>`;
  }
  window.JiaoyingIntakeUI={command,quick};
})();
