import {createHash,randomBytes,timingSafeEqual} from 'node:crypto';
import {isIP} from 'node:net';
export function isPrivateAddress(value=''){const ip=value.replace(/^::ffff:/,'');if(ip==='::1')return true;if(isIP(ip)!==4)return false;const [a,b]=ip.split('.').map(Number);return a===127||a===10||(a===172&&b>=16&&b<=31)||(a===192&&b===168);}
const digest=v=>createHash('sha256').update(String(v||'')).digest(),key=v=>digest(v).toString('hex'),same=(a,b)=>timingSafeEqual(digest(a),digest(b));
const clone=v=>JSON.parse(JSON.stringify(v)),check=(v,m)=>{if(!v)throw Error(m);};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const filterKeys=(o,ids)=>Object.fromEntries(Object.entries(o||{}).filter(([id])=>ids.has(id)));
export function createRoomAccess({roomId,token,allowedHosts}){
  check(/^[a-zA-Z0-9-]{4,40}$/.test(roomId||'')&&typeof token==='string'&&token.length>=32,'房间编号或加入密钥无效');
  const hosts=new Set(['127.0.0.1','localhost','[::1]',...(allowedHosts||[])]);check(![...hosts].some(h=>!['localhost','[::1]'].includes(h)&&!isPrivateAddress(h)),'房间只允许回环或私有 IPv4 地址');
  const cookieName='jiaoying_room_'+roomId,sessions=new Map(),invitations=new Map(),attempts=new Map();
  function principal(req){if(req.headers['sec-fetch-site']==='cross-site')return null;const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'=')),u=c?sessions.get(key(c.slice(cookieName.length+1))):null;return u&&(u.role==='commander'||invitations.has(u.invitationId))?u:null;}
  function active(u,d){if(!u||u.sessionId&&sessions.get(u.sessionId)!==u)return false;if(u.role==='commander')return true;if(!invitations.has(u.invitationId)||u.exerciseId!==d.exerciseId)return false;const v=d.scenario.vehicles.find(x=>x.id===u.vehicleId),s=d.scenario.staff?.find(x=>x.id===u.staffId);return !!(v&&s&&s.available&&(v.driverId===u.staffId||(v.escortIds||[]).includes(u.staffId)));}
  function connection(u){const command=u.role==='commander';return {role:u.role,vehicleId:u.vehicleId||null,staffId:u.staffId||null,scopeLabel:command?'同 Wi-Fi 房间 · 指挥员':'同 Wi-Fi 房间 · 本车任务与本人补报',permissions:{command,manageResources:command,publish:command,finishTask:command,manageAccess:command,readAll:command,fieldProgress:true,fieldReport:true}};}
  function project(d,u){
    if(u.role==='commander')return d;
    const v=d.scenario.vehicles.find(v=>v.id===u.vehicleId),f=d.fleet[u.vehicleId],r=d.activePlan?.routes.find(r=>r.vehicleId===u.vehicleId);
    const ids=new Set([...(r?.stops||[]).map(x=>x.id),...(r?.onboard||[]),...(r?.passengerIds||[]),...(f?.onboard||[]),...(f?.delivered||[])]),crew=new Set([u.staffId,v?.driverId,...(v?.escortIds||[])]),houses=d.scenario.households.filter(h=>ids.has(h.id));
    const nodes=d.scenario.nodes.map(n=>n.kind==='home'&&!houses.some(h=>h.node===n.id)?{...n,label:(d.villages||[]).flatMap(v=>v.pickups||[]).find(p=>p.node===n.id)?.name||'可上报点位'}:n),nodeIds=new Set(nodes.map(n=>n.id));
    const shelters=d.scenario.shelters.filter(s=>s.id===r?.shelterId||s.nodeId===f?.node||s.id===f?.node),shelterIds=new Set(shelters.map(s=>s.id));
    const own=x=>x.roomOrigin?.staffId===u.staffId&&x.roomOrigin?.vehicleId===u.vehicleId&&x.roomOrigin?.exerciseId===u.exerciseId;
    const reports=d.reports.filter(own),villageReports=(d.villageReports||[]).filter(own).map(x=>({...x,householdIds:x.householdIds.filter(id=>ids.has(id))})),reportIds=new Set(reports.map(x=>x.id)),villageIds=new Set(villageReports.map(x=>x.id));
    const fieldEvents=(d.fieldEvents||[]).filter(e=>e.vehicleId===u.vehicleId||reportIds.has(e.reportId)||villageIds.has(e.villageReportId));
    const activePlan=r?{id:d.activePlan.id,inputVersion:d.activePlan.inputVersion,executionVersion:d.activePlan.executionVersion,publishedAt:d.activePlan.publishedAt,routes:[clone(r)],servedIds:[...ids],servedPeople:r.people,totalPeople:r.people,finish:r.finish,unassigned:[],unservedIds:[],unservedPeople:0,unserved:[],wait:r.wait,drive:r.drive}:null;
    return {schema:d.schema,exerciseId:d.exerciseId,createdAt:d.createdAt,revision:d.revision,inputVersion:d.inputVersion,executionVersion:d.executionVersion,algorithm:d.algorithm,phase:d.phase,executionMode:d.executionMode,weather:clone(d.weather),scenarioPreset:d.scenarioPreset,
      scenario:{name:d.scenario.name,region:clone(d.scenario.region),resourceRegistryVersion:d.scenario.resourceRegistryVersion,households:clone(houses),vehicles:v?[clone(v)]:[],staff:clone((d.scenario.staff||[]).filter(s=>crew.has(s.id))),shelters:clone(shelters),nodes:clone(nodes),edges:clone(d.scenario.edges.filter(e=>nodeIds.has(e.from)&&nodeIds.has(e.to)))},
      stage:filterKeys(d.stage,ids),contacts:filterKeys(d.contacts,ids),fleet:f?{[u.vehicleId]:clone(f)}:{},occupancy:filterKeys(d.occupancy,shelterIds),taskAcks:d.taskAcks?.[u.vehicleId]?{[u.vehicleId]:clone(d.taskAcks[u.vehicleId])}:{},villages:clone(d.villages||[]),reports:clone(reports),villageReports:clone(villageReports),fieldEvents:clone(fieldEvents),activePlan,plan:null,baseline:null,alternative:null,planSnapshot:null,history:[],log:[],taskArchives:[],followups:{},taskLifecycle:{status:d.taskLifecycle?.status||'active',endedAt:d.taskLifecycle?.endedAt||null,note:'',summary:null},lastAnnouncement:'已同步本车任务与本人补报。'};
  }
  function authorizeAction(u,action,payload,d){check(active(u,d),'现场身份或车辆编组已变化，请联系指挥员重新发送绑定链接');if(u.role==='commander')return payload;check(['field-progress','field-contact-batch','start-vehicle','report','village-report'].includes(action),'执行人员只能提交本车执行回执和现场补报，该操作需要指挥员权限');if(['field-progress','field-contact-batch','start-vehicle'].includes(action))check(payload.vehicleId===u.vehicleId,'只能登记绑定车辆的执行进度，不能代其他车辆提交回执');if(action==='village-report')check(payload.mode==='increment','现场补报仅增加新发现人员；更正与总量盘点请联系指挥员核对');return {...payload,reporter:u.staffId};}
  function tagNewRecords(before,after,u){if(u.role!=='field')return after;const origin={staffId:u.staffId,vehicleId:u.vehicleId,exerciseId:u.exerciseId};for(const field of ['reports','villageReports','fieldEvents']){const old=new Set((before[field]||[]).map(x=>x.id));for(const x of after[field]||[])if(!old.has(x.id))x.roomOrigin=origin;}return after;}
  function createInvitation(d,{vehicleId,staffId}={}){check(typeof vehicleId==='string'&&typeof staffId==='string','请选择车辆和工作人员编号');const v=d.scenario.vehicles.find(x=>x.id===vehicleId),s=d.scenario.staff?.find(x=>x.id===staffId);check(v&&s&&s.available&&(v.driverId===staffId||(v.escortIds||[]).includes(staffId)),'工作人员必须已到岗并已编入这辆车，请先在资源库核对编组');check(invitations.size<150,'邀请已达 150 条，请撤销不用的邀请后重试');const invitationId=randomBytes(9).toString('hex'),secret=randomBytes(32).toString('base64url'),createdAt=new Date().toISOString();invitations.set(invitationId,{invitationId,tokenHash:key(secret),vehicleId,staffId,exerciseId:d.exerciseId,createdAt});return {invitationId,vehicleId,staffId,createdAt,role:'field',joinPath:'/join#'+secret};}
  return {roomId,principal,active,connection,project,authorizeAction,tagNewRecords,createInvitation,
    invitationList:()=>[...invitations.values()].map(({tokenHash,...item})=>({...item,role:'field'})),
    revoke(id){check(invitations.has(id),'邀请不存在或已经撤销');invitations.delete(id);for(const [key,u] of sessions)if(u.invitationId===id)sessions.delete(key);},
    acceptsHost:h=>hosts.has(h),acceptsAddress:isPrivateAddress,authorized:req=>!!principal(req),
    join(req,candidate,data){const address=req.socket.remoteAddress,now=Date.now(),old=attempts.get(address);if(!old&&attempts.size>=256)attempts.delete(attempts.keys().next().value);const bucket=old&&now-old.since<60000?old:{since:now,count:0};bucket.count++;attempts.set(address,bucket);if(bucket.count>12)return {status:429,error:'加入尝试过多，请一分钟后重试'};if(typeof candidate!=='string'||candidate.length>200)return {status:401,error:'加入链接无效'};let u;if(same(candidate,token))u={role:'commander'};else{const i=[...invitations.values()].find(i=>same(key(candidate),i.tokenHash));if(i)u={role:'field',invitationId:i.invitationId,vehicleId:i.vehicleId,staffId:i.staffId,exerciseId:i.exerciseId};}if(!u||data&&!active(u,data))return {status:401,error:'链接无效、已撤销或编组变化，请向指挥员获取本场链接'};if(sessions.size>=256)sessions.delete(sessions.keys().next().value);const previous=principal(req);if(previous?.sessionId)sessions.delete(previous.sessionId);const secret=randomBytes(32).toString('base64url');u.sessionId=key(secret);sessions.set(u.sessionId,u);return {status:200,cookie:`${cookieName}=${secret}; Path=/; HttpOnly; SameSite=Strict`,connection:connection(u)};},
    page(){return shell('加入叫应演练房间',`<small>叫应 AI · 同 Wi-Fi 房间 ${esc(roomId)}</small><h1>使用指挥员发来的专属链接</h1><p>现场链接绑定车辆和工作人员编号，只能登记本车进展和现场补报。</p><form id="join"><label>加入码<input id="key" type="password" autocomplete="off" placeholder="完整链接会自动填入" required></label><button id="submit">加入本场任务</button></form><p id="status" role="status"></p><div id="links" hidden></div>`,String.raw`
const key=document.getElementById('key'),form=document.getElementById('join'),status=document.getElementById('status'),submit=document.getElementById('submit');try{key.value=decodeURIComponent(location.hash.slice(1));}catch(_){status.textContent='链接格式有误，请重新获取。';}history.replaceState(null,'','/join');form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;status.textContent='正在加入…';try{const response=await fetch('/api/v3/room/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:key.value})}),result=await response.json();if(!response.ok)throw Error(result.error||'加入失败');key.value='';form.hidden=true;const links=document.getElementById('links');links.hidden=false;if(result.connection.role==='commander'){links.innerHTML='<a href="/#command">打开指挥台</a> <a href="/room/manage" class="secondary">给执行人员发链接</a>';status.textContent='已作为指挥员加入。请从人员接入管理生成现场链接。';}else{links.innerHTML='<a href="/#field">打开我的执行任务</a>';status.textContent='已绑定车辆 '+result.connection.vehicleId+' · 工作人员 '+result.connection.staffId;}}catch(error){status.textContent=error.message;}finally{submit.disabled=false;}});`);},
    managePage(addresses=[]){return shell('执行人员接入管理',`<small>叫应 AI · 指挥员专用</small><h1>给执行人员生成专属链接</h1><p>先在资源库编组，再选择车辆与人员，复制现场链接给对应人员。</p><a class="secondary" href="/#command">返回指挥台</a><form id="invite"><label>手机访问地址<select id="address">${addresses.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>车辆<select id="vehicle" required></select></label><label>执行人员编号<select id="staff" required></select></label><button id="create">生成现场端链接</button></form><p id="status" role="status"></p><div id="result" hidden><label>只向对应人员发送这条现场链接<input id="url" readonly></label><button id="copy" type="button">复制现场链接</button></div><h2>已生成的现场邀请</h2><div id="invitations"></div>`,String.raw`
let state;const vehicle=document.getElementById('vehicle'),staff=document.getElementById('staff'),status=document.getElementById('status');const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function request(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})}),d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}function people(){const v=state.data.scenario.vehicles.find(x=>x.id===vehicle.value),ids=[v?.driverId,...(v?.escortIds||[])];staff.innerHTML='<option value="">请选择已到岗的编组人员</option>'+state.data.scenario.staff.filter(x=>x.available&&ids.includes(x.id)).map(x=>'<option value="'+safe(x.id)+'">'+safe(x.id)+'</option>').join('');}async function list(){const d=await request('/api/v3/room/invitations');document.getElementById('invitations').innerHTML=d.invitations.length?d.invitations.map(x=>'<p>'+safe(x.vehicleId)+' · '+safe(x.staffId)+' <button type="button" data-revoke="'+safe(x.invitationId)+'">撤销访问</button></p>').join(''):'<p>尚未生成现场邀请。</p>';}async function refresh(){state=await request('/api/v3/state');state.data.scenario.staff=state.data.scenario.staff||[];vehicle.innerHTML='<option value="">请选择车辆</option>'+state.data.scenario.vehicles.map(x=>'<option value="'+safe(x.id)+'">'+safe(x.name)+' · '+safe(x.id)+'</option>').join('');people();await list();}vehicle.addEventListener('change',people);document.getElementById('invite').addEventListener('submit',async e=>{e.preventDefault();document.getElementById('create').disabled=true;try{const d=await request('/api/v3/room/invitations',{vehicleId:vehicle.value,staffId:staff.value});document.getElementById('url').value=document.getElementById('address').value+d.joinPath;document.getElementById('result').hidden=false;status.textContent='已生成 '+d.vehicleId+' / '+d.staffId+' 的现场链接，不含指挥权限。';await list();}catch(error){status.textContent=error.message;}finally{document.getElementById('create').disabled=false;}});document.getElementById('copy').addEventListener('click',async()=>{const input=document.getElementById('url');input.select();try{await navigator.clipboard.writeText(input.value);status.textContent='现场链接已复制。';}catch(_){document.execCommand('copy');status.textContent='链接已选中；如未复制成功，请按 Ctrl+C 或长按复制。';}});document.getElementById('invitations').addEventListener('click',async e=>{if(!e.target.dataset.revoke)return;try{await request('/api/v3/room/revoke',{invitationId:e.target.dataset.revoke});status.textContent='邀请及对应已登录现场端已撤销。';await list();}catch(error){status.textContent=error.message;}});refresh().catch(error=>status.textContent=error.message);`);}
  };
}
function shell(title,body,script){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${esc(title)}</title><style>body{font:17px/1.7 system-ui;margin:0;background:#edf5f8;color:#173e50;padding:30px 18px}main{max-width:680px;background:white;margin:auto;padding:28px;border-radius:20px}small{color:#527383}input,select,button,a{box-sizing:border-box;font:inherit;border-radius:10px}input,select{width:100%;padding:12px;border:1px solid #acc6d2;margin:8px 0 16px}button,a{border:0;padding:11px 18px;background:#008980;color:white;cursor:pointer;text-decoration:none;display:inline-block}button:disabled{opacity:.6}a.secondary{background:#e8f3f6;color:#173e50}#status{min-height:2em}[hidden]{display:none!important}h1{font-size:25px}h2{font-size:21px}label{display:block}</style></head><body><main>${body}<p><small>同 Wi-Fi 演练。手机 HTTP 页面可能无法启用浏览器麦克风，可用系统键盘语音听写。新建任务、重新编组或撤销邀请后，请获取新的专属链接。</small></p></main><script>${script}</script></body></html>`;}
