/* Presentation for the whole-task lifecycle; all transitions remain server actions. */
(function(root){
  'use strict';
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const time=x=>x?new Date(x).toLocaleString('zh-CN'):'—';
  const closed=state=>['completed','stopped'].includes(state.data.taskLifecycle?.status);
  const summary=state=>state.taskSummary||state.data.taskLifecycle?.summary||{...state.metrics,canComplete:false};
  const button=(label,ac,id='',kind='')=>`<button type="button" class="${kind}" data-ac="${ac}" data-id="${esc(id)}">${label}</button>`;
  function steps(items,current=0){return `<ol class="operation-steps" aria-label="本页操作流程">${items.map((label,i)=>`<li ${i===current?'aria-current="step"':''}><span>${i+1}</span>${esc(label)}</li>`).join('')}</ol>`;}
  function counts(x){return `<dl class="task-counts"><div><dt>已核验完成</dt><dd>${x.verified||0}<small> 人</small></dd></div><div><dt>仍待接送</dt><dd>${x.waiting||0}<small> 人</small></dd></div><div><dt>车上 / 到达待核验</dt><dd>${x.boarded||0}<small> / </small>${x.arrived||0}<small> 人</small></dd></div><div><dt>上报待核实</dt><dd>${x.pendingReports||0}<small> 条</small></dd></div></dl>${x.pendingReviewPeople?`<p class="boundary">另有待核实增报 ${x.pendingReviewPeople} 人，尚未计入有效转移人数。</p>`:''}${x.unplannedPeople?`<p class="boundary">待接人数中有 ${x.unplannedPeople} 人待补接送信息${x.unlocatedPeople?'（其中 '+x.unlocatedPeople+' 人待定位）':''}。</p>`:''}${x.unresolvedReports?`<p class="boundary">另有 ${x.unresolvedReports} 条现场事项尚未处理完毕。</p>`:''}`;}
  function bar(state,view){const d=state.data,done=closed(state),x=summary(state);return `<section class="task-lifecycle-bar ${done?'is-ended':''}" id="task-lifecycle-bar" aria-label="当前整场任务"><div><span class="task-state-dot"></span><strong>${done?(d.taskLifecycle.status==='completed'?'本场任务已完成':'本场任务已提前结束'):d.activePlan?'任务进行中':'任务待发布'}</strong><span class="task-bar-detail">${done?time(d.taskLifecycle.endedAt):'已核验 '+(x.verified||0)+' / '+(x.people||0)+' 人'} · ${esc(d.exerciseId||'当前演练')}</span></div><div class="actions">${view==='command'?(done?button('开始新任务','new-task-dialog','','primary'):button('结束当前任务','end-task-dialog','','end-task-button')):''}</div></section>`;}
  function ended(state,view){const d=state.data;return `<section class="panel task-ended"><div class="panel-body"><span class="eyebrow">本场已结束 · 记录保留</span><h2>${d.taskLifecycle.status==='completed'?'这场转移任务已完成':'这场任务已提前结束'}</h2><p>${esc(d.taskLifecycle.note)}</p>${counts(summary(state))}<p class="boundary">两端现为只读。结束不会把待接、车上或待核实人员自动标记为完成。</p><div class="actions">${button('导出完整记录','export')}</div></div></section>`;}
  function endDialog(state){const x=summary(state),complete=x.canComplete===true;return `<h2>结束当前整场任务</h2><p>结束后，指挥台和现场端一起停止提交；当前台账与发布记录全部保留。</p>${counts(x)}<div class="notice ${complete?'':'warn'}"><strong>${complete?'人员均已核验，可以正常完成本场任务':'还有未完成事项，本次将记为“提前结束”'}</strong><p>${complete?'点击确认即可结束，无需输入核验文字。':'未完成人员保持原状态，后续可在任务记录中查看和导出。'}</p></div><details class="compact-disclosure"><summary>补充结束说明（选填）</summary><label for="task-end-note">结束说明</label><textarea id="task-end-note" maxlength="500" placeholder="不填也可以，系统会保存客观的结束摘要。"></textarea></details><input type="hidden" id="task-end-mode" value="${complete?'completed':'stopped'}"><button type="submit" class="${complete?'primary':'danger'}">${complete?'确认完成整场任务':'提前结束并保留记录'}</button>`;}
  function newDialog(state){return `<h2>开始下一场任务</h2><p>当前整场任务会存入“任务记录”，不会清空原来的人员与未完成事项。</p><p>新任务沿用当前路网类型，从 15 人合成演练底数开始。需要的新需求可继续上传或语音录入；上一场的未完成人员不会自动带入。</p><p class="boundary">当前已有 ${(state.data.taskArchives||[]).length} 场历史。为保护本机存储，最多保留 10 场历史、合计 4 MB；达到上限会暂停新建，不自动删除历史。</p><button type="submit" class="primary">保存本场，开始新任务</button>`;}
  function archives(state){const rows=state.data.taskArchives||[];return `<section class="panel task-archives"><div class="panel-head"><div><h2>历史任务 <span class="badge">${rows.length}</span></h2><p>结束后新建下一场，旧任务会保存在这里。</p></div></div><div class="panel-body">${rows.length?rows.slice().reverse().map(row=>`<details class="compact-disclosure"><summary>${row.status==='completed'?'已完成':'提前结束'} · ${time(row.endedAt)} · 已核验 ${row.summary.verified}/${row.summary.people} 人</summary><p>任务 ${esc(row.exerciseId)}</p><p>${esc(row.data.taskLifecycle.note)}</p>${counts(row.summary)}<div class="actions">${button('查看人员与未完成事项','archive-view',row.exerciseId)}${button('导出这一场','archive-export',row.exerciseId)}</div></details>`).join(''):'<p class="empty">还没有历史任务。当前任务的记录在上方，结束后也会保留。</p>'}</div></section>`;}
  function archiveDetail(row){const d=row.data,names={waiting:'仍待接',boarded:'车上',arrived:'到达待核验',verified:'已核验完成'};return `<h2>历史任务记录</h2><p>${esc(row.exerciseId)} · ${time(row.endedAt)}</p>${counts(row.summary)}<p>${esc(d.taskLifecycle.note)}</p><h3>人员原始进度</h3><div class="table-wrap"><table><thead><tr><th>接送组</th><th>人数</th><th>结束时状态</th></tr></thead><tbody>${d.scenario.households.filter(h=>d.stage[h.id]!=='superseded').map(h=>`<tr><td>${esc(h.name)}</td><td>${h.people}</td><td>${esc(names[d.stage[h.id]]||d.stage[h.id])}</td></tr>`).join('')}</tbody></table></div><h3>村级上报</h3>${(d.villageReports||[]).map(r=>`<p>${esc(r.id)} · ${r.people} 人 · ${esc({pending:'待核实',accepted:r.needsInfo?'已采纳待补信息':'已采纳',rejected:'已退回',superseded:'已更正'}[r.status]||r.status)}<br>${esc(r.text)}</p>`).join('')||'<p>无村级上报。</p>'}<h3>现场事项</h3>${d.reports.map(r=>`<p>${esc(r.id)} · ${esc(r.text)} · ${esc({pending:'待核实',accepted:'已采纳',coordination:'待处理',resolved:'已处理',rejected:'未采纳'}[r.status]||r.status)}</p>`).join('')||'<p>无现场事项。</p>'}<div class="actions">${button('导出这一场完整记录','archive-export',row.exerciseId,'primary')}</div>`;}
  function inbox(state,pending){const rows=(pending||[]).filter(x=>/^(village:|report:)/.test(x.key));if(!rows.length)return '<p id="ops-pending" class="workflow-review-empty">暂无现场补报待处理。</p>';return `<section class="panel" id="ops-pending"><div class="panel-head"><div><h2>现场补报待处理 <span class="badge">${rows.length}</span></h2><p>只处理新上报与待补信息，车辆执行进度在“任务执行”。</p></div></div><div class="panel-body">${rows.length?rows.map(x=>`<article class="workflow-review-row"><div><strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p></div>${button('打开处理',x.op,x.id,'primary small')}</article>`).join(''):'<div class="empty">暂无新的补报。录入需求后，进入“任务执行”核对并发布安排。</div>'}</div></section>`;}
  const api={closed,summary,counts,bar,ended,endDialog,newDialog,archives,archiveDetail,inbox,steps};
  if(typeof module==='object'&&module.exports)module.exports=api;else root.JiaoyingWorkflow=api;
})(typeof window==='object'?window:globalThis);
