const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('../exercise.cjs');
function ready(){const x=E.create();x.action('generate');x.action('confirm');x.action('contact',{ids:x.data.scenario.households.map(h=>h.id)});x.action('start');return x;}
function report(x,p){x.action('report',{kind:'road',location:'east',text:'演练道路受阻',...p});const id=x.data.reports[0].id;x.action('review',{id,decision:'accept',note:'演练现场已核实'});return id;}
function valid(x){assert.deepEqual(E.validate(E.snapshot(x.data),x.data.plan),[]);}
test('same snapshot baseline and search are feasible, deterministic and different in coverage',()=>{const i=E.snapshot(E.initial()),before=structuredClone(i),a=E.solve(i),b=E.baseline(i);assert.equal(a.plan.servedPeople,15);assert.equal(b.servedPeople,12);assert.deepEqual(E.validate(i,a.plan),[]);assert.deepEqual(E.validate(i,b),[]);assert.deepEqual(a.plan.servedIds,E.solve(i).plan.servedIds);assert.ok(a.alternative);assert.notDeepEqual(a.plan.routes,a.alternative.routes);assert.deepEqual(i,before);});
test('weather same-grade change preserves draft and published plan; grade crossing only proposes',()=>{const x=ready(),published=x.data.activePlan;x.action('weather',{preset:'small'});assert.deepEqual(x.data.activePlan,published);const version=x.data.inputVersion;x.action('weather',{preset:'strong'});assert.equal(x.data.inputVersion,version+1);assert.deepEqual(x.data.activePlan,published);assert.ok(x.data.plan);assert.ok(x.data.scenario.edges.every(e=>e.open));});
test('pending free text never closes a road or changes execution; rejection also preserves inputs',()=>{const x=ready(),before=x.data;x.action('report',{kind:'road',location:'east',text:'已到达；东桥受阻'});assert.equal(x.data.inputVersion,before.inputVersion);assert.deepEqual(x.data.stage,before.stage);assert.ok(x.data.scenario.edges.find(e=>e.id==='east').open);x.action('review',{id:'R1',decision:'reject',note:'误报已核对'});assert.ok(x.data.scenario.edges.find(e=>e.id==='east').open);});
test('onboard passengers stay on same vehicle and are not picked up or serviced twice after closure',()=>{const x=ready();x.action('step',{vehicleId:'V1'});assert.deepEqual(x.data.fleet.V1.onboard,['H2']);const active=x.data.activePlan;report(x,{});valid(x);const r=x.data.plan.routes.find(r=>r.vehicleId==='V1');assert.equal(r.from,'H2');assert.deepEqual(r.onboard,['H2']);assert.ok(!r.stops.some(s=>s.id==='H2'));assert.deepEqual(x.data.activePlan,active);x.action('confirm');assert.deepEqual(x.data.fleet.V1.onboard,['H2']);});
test('all exits blocked keeps onboard people explicit as held rather than losing them',()=>{const x=ready();x.action('step',{vehicleId:'V1'});const edges=x.data.scenario.edges.filter(e=>e.from==='H2'||e.to==='H2');for(const e of edges)report(x,{location:e.id});valid(x);const r=x.data.plan.routes.find(r=>r.vehicleId==='V1');assert.equal(r.holding,true);assert.deepEqual(r.onboard,['H2']);assert.ok(x.data.plan.unassigned.some(h=>h.id==='H2'&&h.stage==='boarded'));assert.deepEqual(x.data.fleet.V1.onboard,['H2']);});
test('progress makes candidate stale and confirmation rejects it',()=>{const x=ready();x.action('generate');x.action('step',{vehicleId:'V1'});assert.equal(x.data.plan,null);assert.throws(()=>x.action('confirm'),/依据已变化/);});
test('confirmed closure blocks remaining old route until a new route is approved',()=>{const x=ready();const before=x.data.fleet.V2;report(x,{});assert.equal(E.blockedRoute(x.data,x.data.activePlan.routes.find(r=>r.vehicleId==='V2')),true);assert.throws(()=>x.action('step',{vehicleId:'V2'}),/暂停推进/);assert.deepEqual(x.data.fleet.V2,before);x.action('confirm');assert.equal(E.blockedRoute(x.data,x.data.activePlan.routes.find(r=>r.vehicleId==='V2')),false);});
test('arrivals reserve real shelter capacity; repeated planning never double deducts; verification locks',()=>{const x=ready();while(!x.data.fleet.V1.finished)x.action('step',{vehicleId:'V1'});const delivered=x.data.fleet.V1.delivered,occupied=x.data.occupancy;assert.equal(Object.values(occupied).reduce((a,b)=>a+b,0),6);for(const id of delivered)x.action('verify',{id});x.action('generate');valid(x);x.action('generate');assert.deepEqual(x.data.occupancy,occupied);assert.ok(delivered.every(id=>x.data.stage[id]==='verified'));assert.ok(delivered.every(id=>!x.data.plan.servedIds.includes(id)));assert.equal(x.data.plan.routes.find(r=>r.vehicleId==='V1').people,0);});
test('onboard-only route retains its tail and validates with no remaining pickup',()=>{const x=ready();x.action('step',{vehicleId:'V1'});x.action('step',{vehicleId:'V1'});x.action('generate');const r=x.data.plan.routes.find(r=>r.vehicleId==='V1');assert.equal(r.stops.length,0);assert.equal(r.onboard.length,2);assert.equal(r.segments.length,1);valid(x);const p=structuredClone(x.data.plan);p.routes.find(r=>r.vehicleId==='V1').segments=[];assert.ok(E.validate(E.snapshot(x.data),p).length);});
test('new passengers are a new waiting request, do not rewrite existing onboard numbers, and respect chair capacity',()=>{const x=ready();x.action('step',{vehicleId:'V1'});report(x,{kind:'people',location:'H2',people:2,wheelchair:true,text:'新增2人，其中1人需轮椅'});assert.equal(x.data.scenario.households.find(h=>h.id==='H2').people,3);assert.equal(x.data.scenario.households.find(h=>h.id==='H7').people,2);assert.equal(x.data.stage.H7,'waiting');assert.ok(x.data.plan.unassigned.some(h=>h.id==='H7'));valid(x);});
test('oversized additional group remains unassigned and partial confirmation requires coordination note',()=>{const x=ready();report(x,{kind:'people',location:'H5',people:20,text:'新增20人'});assert.ok(x.data.plan.unassigned.some(h=>h.id==='H7'));assert.throws(()=>x.action('confirm'),/协调措施/);x.action('confirm',{note:'未安排人员已记录并请求增援协调'});assert.equal(x.data.activePlan.complete,false);});
test('duplicate road reports resolve one at a time and road reopens only after last obstacle',()=>{const x=ready(),a=report(x,{}),b=report(x,{});x.action('resolve',{id:a,reopen:true,note:'本条障碍已排除'});assert.equal(x.data.scenario.edges.find(e=>e.id==='east').open,false);assert.equal(x.data.reports.find(r=>r.id===a).status,'resolved');x.action('resolve',{id:b,reopen:true,note:'最后一条障碍已排除'});assert.equal(x.data.scenario.edges.find(e=>e.id==='east').open,true);valid(x);});
test('invalid edits roll back; ninth group is supported and 500-person bound rejects additional approval atomically',()=>{const x=E.create();x.action('generate');const before=x.data;assert.throws(()=>x.action('edit',{kind:'households',id:'H1',people:3,risk:99}));assert.deepEqual(x.data,before);report(x,{kind:'people',location:'H5',people:1,text:'新增1人'});report(x,{kind:'people',location:'H5',people:1,text:'再新增1人'});report(x,{kind:'people',location:'H5',people:1,text:'第九组'});assert.equal(x.data.scenario.households.length,9);valid(x);const capped=E.create();capped.action('village-report',{villageId:'VA',mode:'increment',people:485,pickupId:null,assistancePeople:null,wheelchairPeople:null,groupPolicy:'unknown',text:'待补信息的演示批次485人'});capped.action('village-review',{id:'VR1',decision:'accept',note:'核实人数，等待补齐调度信息'});capped.action('report',{kind:'people',location:'H5',people:1,text:'超过500人演示规模'});const pre=capped.data;assert.throws(()=>capped.action('review',{id:capped.data.reports[0].id,decision:'accept',note:'核实新增'}),/最多管理 500/);assert.deepEqual(capped.data,pre);});
test('medical feedback has a separate resolvable coordination flow and never fabricates dispatch',()=>{const x=ready(),active=x.data.activePlan;const id=report(x,{kind:'medical',location:'H5',text:'需要医疗人员协助'});assert.equal(x.data.reports[0].status,'coordination');assert.deepEqual(x.data.activePlan,active);x.action('resolve',{id,note:'演练人工协调专业人员跟进'});assert.equal(x.data.reports[0].status,'resolved');});
