import test from 'node:test';
import assert from 'node:assert/strict';
import {createExerciseServer} from '../local-server.mjs';
import {integrationStatus,prepareCaiyunRequest,normalizeCaiyun} from '../integrations.mjs';
async function setup(t){const {server}=createExerciseServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;return {base,get:()=>fetch(base+'/api/v3/state').then(r=>r.json()),post:body=>fetch(base+'/api/v3/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})};}
test('two independent clients share reports; stale operations rejected; retried ID deduplicated',async t=>{const api=await setup(t),a=await api.get(),b=await api.get();const input={session:a.session,expectedRevision:a.data.revision,requestId:'field-1',action:'report',payload:{kind:'road',location:'east',text:'同步验证倒树'}};assert.equal((await api.post(input)).status,200);const next=await api.get();assert.equal(next.data.reports[0].text,'同步验证倒树');assert.equal(next.data.scenario.edges.find(e=>e.id==='east').open,true);assert.equal((await api.post({...input,requestId:'command-old',expectedRevision:b.data.revision,action:'generate',payload:{}})).status,409);assert.equal((await api.post(input)).status,200);assert.equal((await api.get()).data.reports.length,1);assert.equal((await api.post({...input,payload:{...input.payload,text:'不同内容'}})).status,409);const review={session:next.session,expectedRevision:next.data.revision,requestId:'command-2',action:'review',payload:{id:'R1',decision:'accept',note:'两端核实演练'}};assert.equal((await api.post(review)).status,200);const fresh=await api.get();assert.equal(fresh.data.reports[0].status,'accepted');assert.equal(fresh.data.scenario.edges.find(e=>e.id==='east').open,false);});
test('concurrent same-version mutations result in one success and one conflict',async t=>{const api=await setup(t),a=await api.get(),base={session:a.session,expectedRevision:a.data.revision,action:'weather',payload:{preset:'small'}};const responses=await Promise.all([api.post({...base,requestId:'1'}),api.post({...base,requestId:'2'})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);});
test('foreign origin, bad data, nonexistent APIs and disabled model are bounded',async t=>{const api=await setup(t);assert.equal((await fetch(api.base+'/api/v3/state',{headers:{Origin:'https://unrelated.example'}})).status,403);assert.equal((await fetch(api.base+'/api/v3/action',{method:'POST',headers:{'Content-Type':'application/json'},body:'bad'})).status,400);assert.equal((await fetch(api.base+'/api/v3/agent')).status,501);const status=await fetch(api.base+'/api/ai/status').then(r=>r.json());assert.equal(status.configured,false);assert.equal((await fetch(api.base+'/api/missing')).status,404);assert.equal((await fetch(api.base+'/')).status,200);assert.equal((await fetch(api.base+'/assets/logo-mark.png')).headers.get('content-type'),'image/png');});
test('Caiyun adapter stays disabled and enforces coordinate and precipitation units',()=>{assert.equal(integrationStatus.weather.connected,false);assert.equal(integrationStatus.agent.connected,false);assert.throws(()=>prepareCaiyunRequest({longitude:null,latitude:null,coordinateSystem:null}));const req=prepareCaiyunRequest({longitude:120,latitude:28,coordinateSystem:'test-fixture-not-real-location'});assert.equal(req.enabled,false);assert.match(req.urlTemplate,/120,28\/weather\?unit=metric:v2/);assert.throws(()=>normalizeCaiyun({status:'ok',unit:'metric'}),/单位/);const raw={status:'ok',unit:'metric:v2',server_time:1000,result:{realtime:{status:'ok',precipitation:{local:{intensity:3.5}}},hourly:{status:'failed'}}};const out=normalizeCaiyun(raw,{fetchedAt:new Date(1000*1000).toISOString()});assert.equal(out.intensity,3.5);assert.equal(out.unit,'mm/h');assert.equal(out.stale,false);assert.deepEqual(out.forecast,[]);assert.equal(normalizeCaiyun({status:'ok',unit:'metric:v2',result:{}}).intensity,null);});
