import test from 'node:test';
import assert from 'node:assert/strict';
import {createExerciseServer} from '../local-server.mjs';
import {integrationStatus,prepareCaiyunRequest,normalizeCaiyun} from '../integrations.mjs';
async function setup(t){const {server}=createExerciseServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;return {base,get:()=>fetch(base+'/api/v3/state').then(r=>r.json()),post:body=>fetch(base+'/api/v3/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})};}

test('whole-task close and new task use revision/session checks and preserve immutable archive records',async t=>{
 const api=await setup(t),initial=await api.get();assert.equal(initial.capabilities.taskLifecycle,true);assert.equal(initial.taskSummary.waiting,15);
 const body=(state,action,payload={},requestId=action)=>({session:state.session,expectedRevision:state.data.revision,requestId,action,payload});
 const close=body(initial,'end-task',{mode:'stopped'});assert.equal((await api.post(close)).status,200);const closed=await api.get();assert.equal(closed.data.taskLifecycle.status,'stopped');
 assert.equal((await api.post(body(initial,'generate'))).status,409);const write=await api.post(body(closed,'weather',{rainfall:80}));assert.equal(write.status,422);assert.match((await write.json()).error,/已结束/);
 const fresh=body(closed,'new-task');assert.equal((await api.post(fresh)).status,200);const next=await api.get();assert.equal(next.session,initial.session);assert.equal(next.data.revision,closed.data.revision+1);assert.equal(next.data.taskArchives.length,1);assert.deepEqual(next.data.taskArchives[0].data.stage,closed.data.stage);
 assert.equal((await api.post(fresh)).status,200);assert.equal((await api.post(close)).status,200);assert.equal((await api.get()).data.taskLifecycle.status,'active');assert.equal((await api.get()).data.taskArchives.length,1);
});

test('batch arrival verification rejects stale revisions and invalid members atomically over HTTP',async t=>{
 const api=await setup(t);let state=await api.get(),counter=0;
 const body=(snapshot,action,payload={})=>({session:snapshot.session,expectedRevision:snapshot.data.revision,requestId:'verify-batch-'+(++counter),action,payload});
 const act=async(action,payload={})=>{const response=await api.post(body(state,action,payload));assert.equal(response.status,200);state=await response.json();};
 await act('confirm');await act('contact',{ids:state.data.activePlan.servedIds});await act('start');
 for(const route of state.data.activePlan.routes.filter(r=>r.people))while(!state.data.fleet[route.vehicleId].finished)await act('step',{vehicleId:route.vehicleId});
 const arrived=state,ids=Object.keys(arrived.data.stage);
 const invalid=await api.post(body(arrived,'verify-arrivals',{ids:[ids[0],'missing']}));assert.equal(invalid.status,422);assert.deepEqual((await api.get()).data,arrived.data);
 await act('weather',{rainfall:21});const stale=await api.post(body(arrived,'verify-arrivals',{ids}));assert.equal(stale.status,409);assert.equal((await api.get()).metrics.verified,0);
 const request=body(state,'verify-arrivals',{ids});const accepted=await api.post(request);assert.equal(accepted.status,200);const final=await accepted.json();assert.equal(final.metrics.verified,15);assert.equal(final.metrics.arrived,0);assert.equal(final.data.revision,state.data.revision+1);
 const duplicate=await api.post(request);assert.equal(duplicate.status,200);assert.equal((await duplicate.json()).duplicate,true);assert.equal((await api.get()).data.revision,final.data.revision);
});
test('two independent clients share reports; stale operations rejected; retried ID deduplicated',async t=>{const api=await setup(t),a=await api.get(),b=await api.get();const input={session:a.session,expectedRevision:a.data.revision,requestId:'field-1',action:'report',payload:{kind:'road',location:'east',text:'同步验证倒树'}};assert.equal((await api.post(input)).status,200);const next=await api.get();assert.equal(next.data.reports[0].text,'同步验证倒树');assert.equal(next.data.scenario.edges.find(e=>e.id==='east').open,true);assert.equal((await api.post({...input,requestId:'command-old',expectedRevision:b.data.revision,action:'generate',payload:{}})).status,409);assert.equal((await api.post(input)).status,200);assert.equal((await api.get()).data.reports.length,1);assert.equal((await api.post({...input,payload:{...input.payload,text:'不同内容'}})).status,409);const review={session:next.session,expectedRevision:next.data.revision,requestId:'command-2',action:'review',payload:{id:'R1',decision:'accept',note:'两端核实演练'}};assert.equal((await api.post(review)).status,200);const fresh=await api.get();assert.equal(fresh.data.reports[0].status,'accepted');assert.equal(fresh.data.scenario.edges.find(e=>e.id==='east').open,false);});
test('concurrent same-version mutations result in one success and one conflict',async t=>{const api=await setup(t),a=await api.get(),base={session:a.session,expectedRevision:a.data.revision,action:'weather',payload:{preset:'small'}};const responses=await Promise.all([api.post({...base,requestId:'1'}),api.post({...base,requestId:'2'})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);});
test('foreign origin, bad data, nonexistent APIs and disabled model are bounded',async t=>{const api=await setup(t);assert.equal((await fetch(api.base+'/api/v3/state',{headers:{Origin:'https://unrelated.example'}})).status,403);assert.equal((await fetch(api.base+'/api/v3/action',{method:'POST',headers:{'Content-Type':'application/json'},body:'bad'})).status,400);assert.equal((await fetch(api.base+'/api/v3/agent')).status,501);const status=await fetch(api.base+'/api/ai/status').then(r=>r.json());assert.equal(status.configured,false);assert.equal((await fetch(api.base+'/api/missing')).status,404);assert.equal((await fetch(api.base+'/')).status,200);assert.equal((await fetch(api.base+'/assets/logo-mark.png')).headers.get('content-type'),'image/png');});
test('Caiyun adapter stays disabled and enforces coordinate and precipitation units',()=>{assert.equal(integrationStatus.weather.connected,false);assert.equal(integrationStatus.agent.connected,false);assert.throws(()=>prepareCaiyunRequest({longitude:null,latitude:null,coordinateSystem:null}));const req=prepareCaiyunRequest({longitude:120,latitude:28,coordinateSystem:'test-fixture-not-real-location'});assert.equal(req.enabled,false);assert.match(req.urlTemplate,/120,28\/weather\?unit=metric:v2/);assert.throws(()=>normalizeCaiyun({status:'ok',unit:'metric'}),/单位/);const raw={status:'ok',unit:'metric:v2',server_time:1000,result:{realtime:{status:'ok',precipitation:{local:{intensity:3.5}}},hourly:{status:'failed'}}};const out=normalizeCaiyun(raw,{fetchedAt:new Date(1000*1000).toISOString()});assert.equal(out.intensity,3.5);assert.equal(out.unit,'mm/h');assert.equal(out.stale,false);assert.deepEqual(out.forecast,[]);assert.equal(normalizeCaiyun({status:'ok',unit:'metric:v2',result:{}}).intensity,null);});
