'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const X=require('../exercise.cjs'),T=require('../lifecycle.cjs');
const node='H1';
const intake=(people,villageId='VA')=>({source:'text',rows:[{villageId,pickupId:villageId==='VA'?'P-A1':'P-B1',people,assistancePeople:0,wheelchairPeople:0,groupPolicy:'splittable',text:`新增${people}人，均可分组`} ]});
const publish=x=>{if(!x.fresh())x.action('generate');x.action('confirm');return x.data.activePlan;};
function ready(x,route){const planId=x.data.activePlan.id,vehicleId=route.vehicleId;x.action('field-progress',{stage:'ack',planId,vehicleId});const ids=route.stops.filter(st=>x.data.stage[st.id]==='waiting'&&!x.data.contacts[st.id].contacted).map(st=>st.id);if(ids.length)x.action('field-contact-batch',{planId,vehicleId,householdIds:ids});x.action('start-vehicle',{planId,vehicleId});}
function finishCar(x,id){while(!x.data.fleet[id].finished)x.action('step',{vehicleId:id});}
function setupOneCar(){const x=X.create(X.createBlank({mapMode:'same'}));x.action('configure-resources',{vehicles:[{id:'V1',name:'接送车',start:'D',capacity:4,wheelchair:false,available:true}],shelters:[{id:'S1',name:'接收一处',capacity:20,available:true},{id:'S2',name:'接收二处',capacity:20,available:true}]});return x;}

test('blank starts at zero, is restorable, cannot be declared completed or published',()=>{const x=X.create(X.createBlank());assert.equal(x.data.scenario.region.mapKind,'osm-road-network');assert.equal(X.metrics(x.data).people,0);assert.equal(T.summary(x.data).canComplete,false);x.action('generate');assert.equal(x.data.plan.totalPeople,0);assert.equal(x.data.plan.complete,false);assert.throws(()=>x.action('confirm'),/没有可执行/);assert.throws(()=>x.action('end-task',{mode:'completed'}),/未完成/);assert.doesNotThrow(()=>X.restore(x.data,{external:true}));});

test('upload20 plus reviewed field3 equals23 with no seed passengers',()=>{const x=X.create(X.createBlank());x.action('command-intake',intake(20));assert.equal(X.metrics(x.data).people,20);publish(x);x.action('village-report',{...intake(3,'VB').rows[0],mode:'increment',reporter:'现场',source:'voice'});assert.equal(X.metrics(x.data).people,20);assert.equal(X.taskSummary(x.data).pendingReviewPeople,3);x.action('village-review',{id:x.data.villageReports[0].id,decision:'accept',note:'现场核对已采纳'});assert.equal(X.metrics(x.data).people,23);assert.equal(x.data.plan.totalPeople,23);assert.equal(x.data.plan.servedPeople+x.data.plan.unassigned.reduce((n,r)=>n+r.people,0),23);assert.doesNotThrow(()=>X.restore(x.data));});

test('new blank task retains configured resource capacities and flattens previous facts',()=>{const x=setupOneCar();x.action('command-intake',intake(6));x.action('end-task',{mode:'stopped'});const before=x.data;x.action('new-task',{seedMode:'blank',mapMode:'ruian-roads',name:'下一场'});assert.equal(x.data.taskName,'下一场');assert.equal(X.metrics(x.data).people,0);assert.equal(x.data.scenario.vehicles[0].capacity,4);assert.equal(x.data.scenario.shelters[0].capacity,20);assert.equal(x.data.taskArchives[0].summary.waiting,6);assert.deepEqual(x.data.taskArchives[0].data.stage,before.stage);assert.equal(x.data.taskArchives[0].data.taskArchives,undefined);assert.doesNotThrow(()=>X.restore(x.data));});

test('reset and scenario preserve active passenger facts in closed history',()=>{const x=setupOneCar();x.action('command-intake',intake(6));let p=publish(x);ready(x,p.routes[0]);x.action('step',{vehicleId:'V1'});const original=x.data,boarded=X.metrics(original).boarded;x.action('reset',{seedMode:'blank'});assert.equal(X.metrics(x.data).people,0);assert.equal(x.data.taskArchives[0].summary.boarded,boarded);assert.equal(x.data.taskArchives[0].status,'stopped');assert.deepEqual(x.data.taskArchives[0].data.fleet,original.fleet);x.action('scenario',{id:'normal'});assert.equal(x.data.taskArchives.length,2);assert.equal(x.data.taskArchives[1].summary.boarded,boarded);assert.doesNotThrow(()=>X.restore(x.data));});

test('external replacement preserves current facts and rejects same-task rewind',()=>{const x=setupOneCar();x.action('command-intake',intake(6));const old=x.data;x.action('command-intake',intake(2,'VB'));assert.throws(()=>x.action('restore',{data:old}),/同一任务/);assert.equal(X.metrics(x.data).people,8);const other=X.create(X.createBlank());x.action('restore',{data:other.data});assert.equal(X.metrics(x.data).people,0);assert.equal(x.data.taskArchives[0].summary.people,8);assert.equal(x.data.taskArchives[0].status,'stopped');assert.doesNotThrow(()=>X.restore(x.data));});

test('archive cleanup requires explicit verified backup and selected existing ids',()=>{const x=X.create();x.action('reset');x.action('reset');const original=x.data;assert.throws(()=>x.action('clear-archives',{exerciseIds:[original.taskArchives[0].exerciseId]}),/导出/);assert.deepEqual(x.data,original);assert.throws(()=>x.action('clear-archives',{exerciseIds:[original.exerciseId],backupConfirmed:true}),/当前任务不可删除/);x.action('clear-archives',{exerciseIds:[original.taskArchives[0].exerciseId],backupConfirmed:true});assert.equal(x.data.taskArchives.length,1);assert.equal(x.data.taskArchives[0].exerciseId,original.taskArchives[1].exerciseId);assert.deepEqual(x.data.scenario,original.scenario);assert.doesNotThrow(()=>X.restore(x.data));});

test('one vehicle can depart while others remain uncontacted; cross-car batches and old plans reject atomically',()=>{const x=X.create();const p=publish(x),r=p.routes.find(r=>r.people),other=p.routes.find(other=>other.people&&other.vehicleId!==r.vehicleId);const planId=p.id,vehicleId=r.vehicleId;x.action('field-progress',{stage:'ack',planId,vehicleId});const before=x.data;assert.throws(()=>x.action('field-contact-batch',{planId,vehicleId,householdIds:[r.stops[0].id,other.stops[0].id]}),/本车/);assert.deepEqual(x.data,before);x.action('field-contact-batch',{planId,vehicleId,householdIds:r.stops.map(s=>s.id)});x.action('start-vehicle',{planId,vehicleId});assert.equal(x.data.phase,'executing');assert.equal(x.data.contacts[other.stops[0].id].contacted,false);x.action('step',{vehicleId});assert.ok(X.metrics(x.data).boarded>0);assert.throws(()=>x.action('step',{vehicleId:other.vehicleId}),/发车/);x.action('generate');x.action('confirm');assert.throws(()=>x.action('field-contact-batch',{planId,vehicleId,householdIds:[r.stops[0].id]}),/过期/);assert.throws(()=>x.action('step',{vehicleId}),/方案变化/);assert.doesNotThrow(()=>X.restore(x.data));});

test('resource configuration validates locations, is atomic and cannot rewrite published resources',()=>{const x=X.create(X.createBlank({mapMode:'same'})),data=x.data;assert.throws(()=>x.action('configure-resources',{vehicles:[{...data.scenario.vehicles[0],start:'unknown'}],shelters:data.scenario.shelters}),/起点/);assert.deepEqual(x.data,data);x.action('configure-resources',{vehicles:[{...data.scenario.vehicles[0],id:'CAR4',capacity:10}],shelters:[{id:'H3',name:'临时演练点',capacity:30,available:true}]});assert.equal(x.data.fleet.CAR4.node,'D');assert.equal(x.data.occupancy.H3,0);x.action('command-intake',intake(4));publish(x);const published=x.data;assert.throws(()=>x.action('configure-resources',{vehicles:data.scenario.vehicles,shelters:data.scenario.shelters}),/未发布/);assert.deepEqual(x.data,published);assert.doesNotThrow(()=>X.restore(x.data));});

test('two trips keep each destination occupancy and arrived people while replanning from last shelter',()=>{const x=setupOneCar();x.action('command-intake',intake(8));let plan=publish(x);assert.equal(plan.servedPeople,4);ready(x,plan.routes[0]);finishCar(x,'V1');const first=x.data,firstShelter=first.fleet.V1.node;assert.equal(X.metrics(first).arrived,4);x.action('start-next-trip',{vehicleId:'V1'});assert.equal(x.data.fleet.V1.node,firstShelter);assert.equal(x.data.fleet.V1.finished,false);assert.deepEqual(x.data.occupancy,first.occupancy);assert.deepEqual(x.data.fleet.V1.delivered,first.fleet.V1.delivered);assert.equal(x.data.plan.servedPeople,4);assert.throws(()=>x.action('step',{vehicleId:'V1'}),/发车/);plan=publish(x);ready(x,plan.routes[0]);finishCar(x,'V1');assert.equal(X.metrics(x.data).arrived,8);assert.equal(x.data.fleet.V1.deliveries.length,2);assert.equal(Object.values(x.data.occupancy).reduce((a,b)=>a+b,0),8);assert.equal(x.data.fleet.V1.delivered.length,2);assert.doesNotThrow(()=>X.restore(x.data));const malformed=x.data;malformed.fleet.V1.deliveries[1].householdIds=malformed.fleet.V1.deliveries[0].householdIds;assert.throws(()=>X.restore(malformed),/不守恒/);x.action('verify-arrivals',{ids:x.data.fleet.V1.delivered});x.action('end-task',{mode:'completed'});assert.equal(x.data.taskLifecycle.summary.verified,8);assert.doesNotThrow(()=>X.restore(x.data));});

test('optional resource and review notes record factual defaults',()=>{const x=X.create();x.action('resource-event',{kind:'vehicle',id:'V2',available:false});assert.match(x.data.scenario.vehicles[1].unavailableReason,/人工核对/);x.action('report',{kind:'other',location:node,text:'现场收到通知'});x.action('review',{id:x.data.reports[0].id,decision:'accept'});assert.match(x.data.reports[0].note,/人工核实/);});

test('explicit carryover copies only waiting and accepted incomplete demand with source links',()=>{const x=setupOneCar();x.action('command-intake',intake(8));const plan=publish(x);ready(x,plan.routes[0]);x.action('step',{vehicleId:'V1'});x.action('command-intake',{source:'text',rows:[{villageName:'未定位演练村',people:2,assistancePeople:null,wheelchairPeople:null,groupPolicy:'unknown',text:'新增2人待定位'}]});x.action('village-report',{...intake(3,'VB').rows[0],mode:'increment',reporter:'现场',source:'voice'});x.action('end-task',{mode:'stopped'});const old=x.data;assert.equal(X.metrics(old).boarded,4);assert.equal(X.metrics(old).waiting,6);x.action('new-task',{seedMode:'blank',mapMode:'same',carryWaiting:true});assert.equal(X.metrics(x.data).people,6);assert.equal(X.metrics(x.data).boarded,0);assert.equal(X.taskSummary(x.data).pendingReports,0);assert.equal(X.metrics(x.data).unplannedPeople,2);assert.equal(x.data.carryover.people,6);assert.ok(x.data.villageReports.every(r=>r.carryover.exerciseId===old.exerciseId));assert.ok(x.data.scenario.households.every(h=>h.carryover.householdIds.every(id=>old.stage[id]==='waiting')));assert.equal(x.data.taskArchives[0].summary.boarded,4);assert.equal(x.data.taskArchives[0].summary.pendingReviewPeople,3);assert.doesNotThrow(()=>X.restore(x.data));});

test('resource ids can be generated without overwriting existing ids',()=>{const x=X.create(X.createBlank({mapMode:'same'}));const vehicles=[...x.data.scenario.vehicles,{name:'增援车',start:'D',capacity:6,wheelchair:false,available:true}];x.action('configure-resources',{vehicles,shelters:x.data.scenario.shelters});assert.equal(x.data.scenario.vehicles.length,4);assert.equal(x.data.scenario.vehicles.at(-1).id,'V4');assert.doesNotThrow(()=>X.restore(x.data));});

test('legacy whole-task execution cannot advance next trip using the previous published plan',()=>{const x=setupOneCar();x.action('command-intake',intake(8));publish(x);x.action('contact',{ids:x.data.activePlan.servedIds});x.action('start');finishCar(x,'V1');x.action('start-next-trip',{vehicleId:'V1'});const before=x.data;assert.throws(()=>x.action('step',{vehicleId:'V1'}),/发车/);assert.deepEqual(x.data,before);assert.doesNotThrow(()=>X.restore(x.data));});

test('blank task name is optional and configured vehicle ids and colors survive form roundtrip',()=>{const x=X.create(X.createBlank());x.action('end-task',{mode:'stopped'});x.action('new-task',{seedMode:'blank',name:''});assert.equal(x.data.taskName,'新建转移任务');const old=x.data.scenario.vehicles;const vehicles=old.map(({color,...v})=>v);vehicles.push({id:'',name:'新车辆',capacity:5,start:'D',available:true,wheelchair:false});x.action('configure-resources',{vehicles,shelters:x.data.scenario.shelters});assert.equal(x.data.scenario.vehicles.at(-1).id,'V4');assert.equal(x.data.scenario.vehicles[0].color,old[0].color);assert.doesNotThrow(()=>X.restore(x.data));});

test('adopting per-vehicle workflow preserves other cars already executing in legacy snapshots',()=>{const x=X.create();publish(x);x.action('contact',{ids:x.data.activePlan.servedIds});x.action('start');const legacy=x.data;for(const f of Object.values(legacy.fleet)){delete f.startedPlanId;delete f.tripNumber;}const y=X.create(legacy),p=y.data.activePlan,one=p.routes.find(r=>r.people),two=p.routes.find(r=>r.people&&r.vehicleId!==one.vehicleId);y.action('field-progress',{stage:'ack',planId:p.id,vehicleId:one.vehicleId});y.action('start-vehicle',{planId:p.id,vehicleId:one.vehicleId});assert.equal(y.data.fleet[two.vehicleId].startedPlanId,p.id);y.action('step',{vehicleId:two.vehicleId});assert.ok(y.data.fleet[two.vehicleId].onboard.length);assert.doesNotThrow(()=>X.restore(y.data));});

test('next-trip restores legacy deliveries and can use a different receiving point without moving earlier arrivals',()=>{const x=setupOneCar();x.action('command-intake',intake(8));let p=publish(x);ready(x,p.routes[0]);finishCar(x,'V1');const legacy=x.data;delete legacy.fleet.V1.deliveries;const y=X.create(legacy),first=y.data.fleet.V1.node,other=y.data.scenario.shelters.find(sh=>sh.id!==first).id;y.action('resource-event',{kind:'shelter',id:first,available:false});y.action('start-next-trip',{vehicleId:'V1'});p=publish(y);assert.equal(p.routes[0].shelterId,other);ready(y,p.routes[0]);finishCar(y,'V1');assert.equal(y.data.occupancy[first],4);assert.equal(y.data.occupancy[other],4);assert.equal(y.data.fleet.V1.deliveries[0].shelterId,first);assert.equal(y.data.fleet.V1.deliveries[1].shelterId,other);assert.doesNotThrow(()=>X.restore(y.data));});

test('next-trip draft cannot create a false acknowledgement for a completed old route, while other active cars continue',()=>{
 const x=X.create();const p=publish(x),routes=p.routes.filter(r=>r.people);for(const r of routes)ready(x,r);const first=routes[0],other=routes[1];finishCar(x,first.vehicleId);x.action('start-next-trip',{vehicleId:first.vehicleId});const before=x.data;
 assert.throws(()=>x.action('field-progress',{stage:'ack',planId:p.id,vehicleId:first.vehicleId}),/原方案已完成/);assert.deepEqual(x.data,before);assert.throws(()=>x.action('start-vehicle',{planId:p.id,vehicleId:first.vehicleId}),/条件已变化|原方案已完成/);assert.deepEqual(x.data,before);
 x.action('field-progress',{stage:'board',planId:p.id,vehicleId:other.vehicleId,householdId:other.stops[0].id});assert.ok(x.data.fleet[other.vehicleId].onboard.length);assert.equal(x.data.fleet[first.vehicleId].onboard.length,0);assert.doesNotThrow(()=>X.restore(x.data));
});
