'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const W=require('../dist/task-workbench.js'),E=require('../exercise.cjs');
const base=()=>({vehicles:[{id:'V1',name:'1号车',capacity:4,start:'D',wheelchair:false,available:true}],shelters:[{id:'S1',name:'接收点',capacity:20,available:true}]});
const nodes=['D','H1','S1','S2'];
function dom(initial=base()){
 const lists={vehicle:[],shelter:[]},events={},values={'resource-csv':{value:''},'resource-csv-error':{textContent:''},'resource-editor-error':{textContent:''}};
 const decode=s=>String(s??'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
 function row(kind,data){const fields={name:{value:data.name},capacity:{value:String(data.capacity??'')},node:{value:data.start||data.nodeId||data.id},available:{checked:data.available},wheelchair:{checked:data.wheelchair}};return {dataset:{resourceKind:kind,resourceId:data.id||''},querySelector:s=>fields[s.match(/field="([^"]+)"/)[1]],fields};}
 for(const v of initial.vehicles)lists.vehicle.push(row('vehicle',v));for(const v of initial.shelters)lists.shelter.push(row('shelter',v));
 const editor={dataset:{resourceNodes:JSON.stringify(nodes),nodeOptions:'<option value="">请选择地图位置</option>'+nodes.map(n=>`<option value="${n}">${n}</option>`).join('')},querySelector:s=>({appendChild:r=>lists[s.match(/list="([^"]+)"/)[1]].push(r)}),querySelectorAll:s=>lists[s.match(/kind="([^"]+)"/)[1]]};
 const container={ownerDocument:{createElement(){const r=row('vehicle',{name:'',capacity:'',id:''});Object.defineProperty(r,'innerHTML',{set:html=>{for(const match of html.matchAll(/<(input|select)\b[^>]*data-resource-field="([^"]+)"[^>]*>/g)){const tag=match[0],key=match[2];r.fields[key]={value:decode(tag.match(/\bvalue="([^"]*)"/)?.[1]||''),checked:/\bchecked\b/.test(tag)};}}});return r;}},querySelector:s=>s==='#resource-editor'?editor:values[s.slice(1)],querySelectorAll:()=>[...lists.vehicle,...lists.shelter],addEventListener:(name,fn)=>events[name]=fn,removeEventListener:(name,fn)=>{if(events[name]===fn)delete events[name];}};
 return {container,lists,values,fire(id,dataset={}){const target={id,dataset,hasAttribute:()=>false,closest:()=>target};events.click({target});}};
}

test('resource form escapes attribute labels, preserves selected nodes, and shows explicit empty positions',()=>{const data=E.createBlank();data.scenario.vehicles[0].name='车" onfocus="bad';const html=W.resourceForm({data});assert.match(html,/车&quot; onfocus=&quot;bad容量/);assert.doesNotMatch(html,/aria-label="车" onfocus=/);assert.match(html,/<option value="">请选择地图位置<\/option>/);assert.match(html,/max="10000" step="1" required/);assert.match(html,/车辆编号可留空自动生成/);});

test('resource fields never coerce blank, fractional, negative or out-of-range capacities into saved values',()=>{for(const raw of ['', ' ', '-1','1.5','1e2','Infinity','501']){const d=dom();d.lists.vehicle[0].fields.capacity.value=raw;assert.throws(()=>W.readResources(d.container),/容量/);}const d=dom();d.lists.vehicle[0].fields.capacity.value='0';d.lists.shelter[0].fields.capacity.value='10000';const payload=W.readResources(d.container);assert.equal(payload.vehicles[0].capacity,0);assert.equal(payload.shelters[0].capacity,10000);d.lists.shelter[0].fields.capacity.value='10001';assert.throws(()=>W.readResources(d.container),/10000/);});

test('resource read checks location, duplicate keys and minimum count before submission',()=>{const d=dom();d.lists.vehicle[0].fields.node.value='';assert.throws(()=>W.readResources(d.container),/请选择/);d.lists.vehicle[0].fields.node.value='UNLISTED';assert.throws(()=>W.readResources(d.container),/请选择/);d.lists.vehicle[0].fields.node.value='D';d.lists.vehicle.push(d.lists.vehicle[0]);assert.throws(()=>W.readResources(d.container),/重复/);d.lists.vehicle=[];assert.throws(()=>W.readResources(d.container),/1–30/);});

test('CSV parsing accepts quoted names and empty auto-ids but validates the complete combined table',()=>{const rows=W.parseResourceCSV('类型,编号,名称,容量,位置节点,轮椅位,可用\nvehicle,,"增援,二号",8,D,0,1\nshelter,S2,接收二处,300,S2,0,1',{nodes,existing:base()});assert.equal(rows[0].name,'增援,二号');assert.equal(rows[0].id,'');assert.equal(rows[1].capacity,300);for(const text of ['vehicle,V1,重复车,6,D,0,1','vehicle,V2,未知点,6,UNKNOWN,0,1','vehicle,V2,空容量,,D,0,1','vehicle,V2,大车,501,D,0,1','shelter,S2,溢出,10001,S2,0,1','shelter,SH2,不匹配,20,S2,0,1'])assert.throws(()=>W.parseResourceCSV(text,{nodes,existing:base()}));});

test('add resource leaves capacity and location unset and new car receives an id only on save',()=>{const d=dom(),unbind=W.bindResources(d.container);d.fire('',{resourceAdd:'vehicle'});assert.equal(d.lists.vehicle.length,2);assert.equal(d.lists.vehicle[1].fields.capacity.value,'');assert.equal(d.lists.vehicle[1].fields.node.value,'');assert.equal(d.lists.vehicle[1].dataset.resourceId,'');assert.throws(()=>W.readResources(d.container),/名称|容量|位置/);const row=d.lists.vehicle[1];row.fields.name.value='增援';row.fields.capacity.value='6';row.fields.node.value='D';const payload=W.readResources(d.container),store=E.create(E.createBlank({mapMode:'same'}));store.action('configure-resources',payload);assert.equal(store.data.scenario.vehicles[1].id,'V4');assert.equal(store.data.scenario.vehicles[1].capacity,6);unbind();});

test('CSV DOM handler appends all valid rows but no partial rows on an invalid file',()=>{const d=dom();W.bindResources(d.container);d.values['resource-csv'].value='vehicle,,增援一,8,D,0,1\nvehicle,,错点车,6,NO,0,1';d.fire('resource-csv-parse');assert.equal(d.lists.vehicle.length,1);assert.match(d.values['resource-csv-error'].textContent,/未追加任何/);d.values['resource-csv'].value='vehicle,,增援一,8,D,0,1\nshelter,S2,接收二处,100,S2,0,1';d.fire('resource-csv-parse');assert.equal(d.lists.vehicle.length,2);assert.equal(d.lists.shelter.length,2);assert.match(d.values['resource-csv-error'].textContent,/完整追加 2/);const payload=W.readResources(d.container);assert.equal(payload.vehicles[1].start,'D');assert.equal(payload.shelters[1].capacity,100);});
