'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const X=require('../exercise.cjs'),I=require('../dist/resource-intake.js'),G=require('../dist/resource-registry.js'),W=require('../dist/task-workbench.js');
function payload(x){const s=x.data.scenario;return {resourceRegistryVersion:1,staff:s.staff,vehicles:s.vehicles,shelters:s.shelters};}
function fixture(){const x=X.create(X.createBlank({mapMode:'same'}));x.action('configure-resources',{resourceRegistryVersion:1,staff:[{id:'D01',role:'driver',available:true},{id:'D02',role:'driver',available:true},{id:'E01',role:'escort',available:true}],vehicles:[{id:'V1',name:'接送一号',model:'演练中巴',vehicleType:'minibus',totalCapacity:8,wheelchairSlots:1,driverId:'D01',escortIds:['E01'],notes:'',start:'D',available:true}],shelters:[{id:'S1',name:'演练接收点',capacity:30,available:true}]});return x;}
function context(x){return {...x.data.scenario};}
function publish(x){x.action('command-intake',{source:'text',rows:[{villageId:'VA',pickupId:'P-A1',people:3,assistancePeople:1,wheelchairPeople:0,groupPolicy:'together',text:'三人转移'}]});x.action('confirm');return x.data.activePlan;}
function depart(x){const plan=publish(x);x.action('field-progress',{stage:'ack',vehicleId:'V1',planId:plan.id});x.action('field-contact-batch',{vehicleId:'V1',planId:plan.id,householdIds:plan.routes[0].stops.map(s=>s.id)});x.action('start-vehicle',{vehicleId:'V1',planId:plan.id});return plan;}
test('Excel explicit update preserves unspecified existing resource fields and previews original data',()=>{const x=fixture(),c=context(x),r=I.parseRows('vehicle',[['操作','车辆编号','总核载'],['修改','V1',12]],c);assert.equal(r.rows[0].totalCapacity,12);assert.equal(r.rows[0].driverId,'D01');assert.equal(r.rows[0]._resourceBefore.totalCapacity,8);const out=I.applyDraft('vehicle',r.rows,c);assert.equal(out.length,1);assert.equal(out[0].totalCapacity,12);assert.equal(c.vehicles[0].totalCapacity,8);});
test('speech disable and enable use existing identifiers without duplicating resources',()=>{const x=fixture(),c=context(x),r=I.parseSpeech('staff','停用工作人员D01',c);assert.equal(r.rows[0].intent,'disable');assert.equal(r.rows[0].available,false);assert.equal(r.rows[0].role,'driver');assert.equal(I.applyDraft('staff',r.rows,c).length,c.staff.length);const v=I.parseSpeech('vehicle','修改车辆V1，总核载十二人',c);assert.equal(v.rows[0].targetId,'V1');assert.equal(v.rows[0].totalCapacity,12);assert.throws(()=>I.parseSpeech('vehicle','修改车辆UNKNOWN，总核载十二人',c),/未唯一匹配/);});
test('model null fields do not erase unchanged values but explicit empty crew clears them',()=>{const c=context(fixture()),r=I.parseRows('vehicle',[{intent:'update',targetId:'V1',id:'V1',driverId:'',escortIds:[],totalCapacity:null,explicitFields:['driverId','escortIds']}],c);assert.equal(r.rows[0].totalCapacity,8);assert.equal(r.rows[0].driverId,'');assert.deepEqual(r.rows[0].escortIds,[]);assert.doesNotThrow(()=>I.validateDraft('vehicle',r.rows,c));});
test('invalid model crew grounding cannot silently fall back to old crew during update',()=>{const c=context(fixture()),r=I.parseRows('vehicle',[{intent:'update',targetId:'V1',driverId:null,explicitFields:[],validationIssues:[{field:'driverId',message:'未可靠定位'}]}],c);assert.throws(()=>I.validateDraft('vehicle',r.rows,c),/司机编号/);r.rows[0].driverId='D02';assert.doesNotThrow(()=>I.validateDraft('vehicle',r.rows,c));});
test('mixed duplicate target batch rejects atomically and replacing one vehicle cannot take another driver',()=>{const c=context(fixture()),raw=[['操作','车辆编号','总核载'],['修改','V1',10],['修改','V1',12]],r=I.parseRows('vehicle',raw,c);assert.throws(()=>I.applyDraft('vehicle',r.rows,c),/重复/);assert.equal(c.vehicles[0].totalCapacity,8);});
test('published unstarted vehicle can change crew and additions preserve current plan and acknowledgements',()=>{const x=fixture();publish(x);const before=x.data,p=payload(x);p.vehicles[0].driverId='D02';x.action('configure-resources',p);assert.equal(x.data.scenario.vehicles[0].driverId,'D02');assert.deepEqual(x.data.activePlan,before.activePlan);assert.deepEqual(x.data.fleet,before.fleet);assert.equal(X.blockedRoute(x.data,before.activePlan.routes[0]),true);assert.doesNotThrow(()=>X.restore(x.data,{external:true}));});
test('reinforcements after boarding preserve fleet, occupancy and publication history without rewinding time',()=>{const x=fixture();depart(x);x.action('step',{vehicleId:'V1'});const before=x.data,p=payload(x);p.staff.push({id:'D03',role:'driver',available:true});p.vehicles.push({...p.vehicles[0],id:'V2',name:'增援二号',driverId:'D03',escortIds:[],start:'D'});x.action('configure-resources',p);assert.deepEqual(x.data.fleet.V1,before.fleet.V1);assert.deepEqual(x.data.occupancy,before.occupancy);assert.deepEqual(x.data.history,before.history);assert.deepEqual(x.data.activePlan,before.activePlan);assert.ok(x.data.fleet.V2.minute>=before.fleet.V1.minute);assert.equal(x.data.plan.routes.find(r=>r.vehicleId==='V1').onboard.length,1);assert.doesNotThrow(()=>X.restore(x.data,{external:true}));});
test('departed vehicle capacity, crew and position edits are rejected before any partial write',()=>{for(const edit of [p=>p.vehicles[0].totalCapacity=12,p=>p.vehicles[0].driverId='D02',p=>p.vehicles[0].start='S1',p=>p.staff[0].role='reserve']){const x=fixture();depart(x);const before=x.data,p=payload(x);edit(p);assert.throws(()=>x.action('configure-resources',p),/已出发|角色|出发位置/);assert.deepEqual(x.data,before);}});
test('existing resources cannot be removed after publish and unavailable reinforcements are not assumed available',()=>{const x=fixture();publish(x);const before=x.data,p=payload(x);p.staff=p.staff.filter(s=>s.id!=='D02');assert.throws(()=>x.action('configure-resources',p),/不能移除/);assert.deepEqual(x.data,before);const q=payload(x);q.staff.push({id:'D03',role:'driver',available:false});assert.throws(()=>x.action('configure-resources',q),/核实到岗/);assert.deepEqual(x.data,before);});
test('resource updates retain shelter occupancy and cannot lower capacity below accepted people',()=>{const x=fixture();depart(x);x.action('step',{vehicleId:'V1'});x.action('step',{vehicleId:'V1'});const before=x.data,p=payload(x);p.shelters[0].capacity=2;assert.throws(()=>x.action('configure-resources',p),/已接收人数/);assert.deepEqual(x.data,before);p.shelters[0].capacity=40;x.action('configure-resources',p);assert.equal(x.data.occupancy.S1,3);assert.deepEqual(x.data.fleet.V1,before.fleet.V1);});
test('running resource availability changes remain possible and force confirmation before affected routes resume',()=>{const x=fixture();depart(x);const before=x.data,p=payload(x);p.staff[0].available=false;x.action('configure-resources',p);assert.equal(X.blockedRoute(x.data,before.activePlan.routes[0]),true);assert.deepEqual(x.data.fleet,before.fleet);const restore=payload(x);restore.staff[0].available=true;x.action('configure-resources',restore);assert.equal(X.blockedRoute(x.data,before.activePlan.routes[0]),true);});
test('shelter disable and restore through resource editor still require renewed plan confirmation',()=>{const x=fixture();depart(x);const before=x.data,p=payload(x);p.shelters[0].available=false;x.action('configure-resources',p);const q=payload(x);q.shelters[0].available=true;x.action('configure-resources',q);assert.equal(X.blockedRoute(x.data,before.activePlan.routes[0]),true);assert.deepEqual(x.data.activePlan,before.activePlan);});
test('execution form explains increment-only resource scope and exact vehicle locks',()=>{const x=fixture();depart(x);const html=W.resourceForm({data:x.data});assert.match(html,/可补充增援并调整未出发车辆/);assert.match(html,/data-readonly="false"/);assert.match(html,/data-resource-policy=/);assert.deepEqual(G.resourceChangePolicy(x.data).lockedVehicleIds,['V1']);});
test('retained published resource snapshots survive repeated updates but reject forged derived capacities',()=>{const x=fixture();publish(x);const p=payload(x);p.vehicles[0].driverId='D02';x.action('configure-resources',p);x.action('confirm');const q=payload(x);q.vehicles[0].totalCapacity=10;x.action('configure-resources',q);assert.doesNotThrow(()=>X.restore(x.data,{external:true}));const bad=x.data;const first=Object.values(bad.resourcePlanSnapshots)[0];first.vehicles[0].capacity++;assert.throws(()=>X.restore(bad,{external:true}),/可接人数/);const unknown=x.data;Object.values(unknown.resourcePlanSnapshots)[0].households=[];assert.throws(()=>X.restore(unknown,{external:true}),/资源历史快照/);});
test('legacy published resources retain an explanatory boundary instead of guessing total capacity or crews',()=>{const x=X.create();x.action('generate');x.action('confirm');const html=W.resourceForm({data:x.data});assert.match(html,/旧任务尚未登记总核载和工作人员编号/);assert.match(html,/data-readonly="true"/);assert.doesNotMatch(html,/type="submit"/);});
